USE ESQUINA_VENDAS

-- BACKUP
-- FULL BACKUP -- INIT (INICIAL) / NOINIT (ADICIONA UM FULL EM UM EXISTENTE)
-- DIFERENCIAL BACKUP
-- TRANSACT BACKUP

-- FULL
BACKUP DATABASE ESQUINA_VENDAS TO DISK = 'C:\TEMP SQL\ESQUINA_VENDAS.BAK' WITH INIT -- FULL

BACKUP DATABASE ESQUINA_VENDAS TO DISK = 'C:\TEMP SQL\ESQUINA_VENDAS.BAK' WITH NOINIT -- FULL

BACKUP DATABASE ESQUINA_VENDAS TO DISK = 'C:\TEMP SQL\ESQUINA_VENDAS_COMPRESSION.BAK' WITH COMPRESSION -- FULL COMPRIMIDO

-- TRANSAÇÃO
BACKUP LOG ESQUINA_VENDAS TO DISK = 'C:\TEMP SQL\ESQUINA_VENDAS_LOG.BAK' WITH INIT

BACKUP LOG ESQUINA_VENDAS TO DISK = 'C:\TEMP SQL\ESQUINA_VENDAS.BAK' WITH NOINIT

-- DIFERENCIAL
BACKUP DATABASE ESQUINA_VENDAS TO DISK = 'C:\TEMP SQL\ESQUINA_VENDAS_DIF.BAK' WITH DIFFERENTIAL

BACKUP DATABASE ESQUINA_VENDAS TO DISK = 'C:\TEMP SQL\ESQUINA_VENDAS.BAK' WITH DIFFERENTIAL

-------------- BACKUP DE TESTE -----------

CREATE DATABASE TESTE
USE TESTE

-- PS.: TABELA TESTE VEIO JUNTO COM O MODEL CRIADO

SELECT * FROM TESTE

-- PRIMEIRO
INSERT INTO TESTE (NOME)
VALUES ('A')

-- FULL
BACKUP DATABASE TESTE TO DISK = 'C:\TEMP SQL\TESTE.BAK' WITH INIT

-- SEGUNDO
INSERT INTO TESTE (NOME)
VALUES ('B')

-- TRANSACTION
BACKUP LOG TESTE TO DISK = 'C:\TEMP SQL\TESTE.BAK' WITH NOINIT

-- TERCEIRO
INSERT INTO TESTE (NOME)
VALUES ('C')

-- BACKUP DIFERENCIAL
BACKUP DATABASE TESTE TO DISK = 'C:\TEMP SQL\TESTE.BAK' WITH DIFFERENTIAL

-- VERIFICAÇÃO DO ARQUIVO DE BACKUP (VÁLIDO = 1)
RESTORE VERIFYONLY FROM DISK = 'C:\TEMP SQL\TESTE.BAK'

-- VERIFICAÇÃO DO CABEÇALHO DO BACKUP
RESTORE HEADERONLY FROM DISK = 'C:\TEMP SQL\TESTE.BAK'

-- RECUPERAÇÃO DO BANCO DE DADOS

USE MASTER -- MUDAR DE BANCO PARA CONSEGUIR ALTERAR E EXCLUIR

ALTER DATABASE TESTE SET SINGLE_USER WITH ROLLBACK IMMEDIATE -- SOMENTE UM USUÁRIO PODE USAR O DATABASE / ALTERANDO O STATUS POR QUESTÃO DE SEGURANÇA SOMENTE PARA MEU USUÁRIO

-- ALTER DATABASE TESTE SET MULTI_USER WITH ROLLBACK IMMEDIATE --> VOLTAR PARA VÁRIOS USUÁRIOS

DROP DATABASE TESTE -- EXCLUIR O DB

-- RESTAURAR O DB EXCLUIDO
RESTORE DATABASE TESTE FROM DISK = 'C:\TEMP SQL\TESTE.BAK' WITH FILE = 1, NORECOVERY -- FILE = 1 --> POSITION NO RESTORE HEADERONLY / PODE MUDAR PARA A POSITION QUE QUISER (MAS SEMPRE ANTES TEM QUE EXISTIR UMA VERSÃO FULL)
RESTORE DATABASE TESTE FROM DISK = 'C:\TEMP SQL\TESTE.BAK' WITH FILE = 2, NORECOVERY -- FILE = 1 : FULL / FILE = 2 : LOG (TRANSACT) (NESTE EXEMPLO)
RESTORE DATABASE TESTE FROM DISK = 'C:\TEMP SQL\TESTE.BAK' WITH FILE = 3, RECOVERY -- FILE = 3 : DIFFERENTIAL (NESTE EXEMPLO)

-- RECOVERY = USAMOS ESTA OPÇÃO QUANDO NÃO VAMOS MAIS LER OUTROS ARQUIVOS DE BACKUP
-- NORECOVERY = USAMOS ESTA OPÇÃO QUANDO VAMOS LER OUTROS ARQUIVOS DE BACKUP

-- BACKUP TYPE 1 = FULL
-- BACKUP TYPE 2 = TRANSACT
-- BACKUP TYPE 5 = DIFFERENTIAL
