USE ESQUINA_VENDAS

-- TRIM
SELECT LTRIM('                   OLA') AS 'CAMPO'

SELECT TRIM ('      OLA      ') AS 'CAMPO'

SELECT RTRIM('OLA       ') AS 'CAMPO'

--REPLACE

SELECT REPLACE(TRIM('      HELOISA BONILHA     '),'I','Í')

SELECT REPLACE('AVENIDA RUA 123', 'AVENIDA','ESTRADA')
-- CONCAT

SELECT CONCAT('OLA ','MUNDO') AS 'CAMPO'

SELECT CONCAT(NOME,' -> ',CPF) AS 'CAMPO' FROM [dbo].[TABELA DE CLIENTES]

SELECT NOME AS 'NOME CLIENTE',CONCAT([ENDERECO],' | ',[BAIRRO],' | ',[CIDADE],' | ',[ESTADO]) AS 'ENDEREÇO COMPLETO' FROM [dbo].[TABELA DE CLIENTES]

--LEFT/RIGHT

SELECT LEFT('AVENIDA RUA 123', 7) AS 'CAMPO'

SELECT RIGHT('AVENIDA RUA 123', 3) AS 'CAMPO'

-- LOWER/UPPER
SELECT LOWER('AVENIDA RUA 123') AS 'CAMPO'

SELECT UPPER('avenida rua 123') AS 'CAMPO'

-- SUBSTRING

SELECT SUBSTRING('AVENIDA RUA 123',1,11) AS 'CAMPO'

--LEN

SELECT LEN('AVENIDA RUA 123') AS 'CAMPO'

-- FUNÇÕES DATAS

SELECT SYSDATETIME() AS 'DATA ATUAL DO SISTEMA'

SELECT SYSDATETIMEOFFSET() AS 'DATA ATUAL DO SISTEMA COM FUSO HORÁRIO'

SELECT SYSUTCDATETIME() AS 'HORÁRIO UTC'

SELECT CURRENT_TIMESTAMP

SELECT GETDATE()

SELECT GETUTCDATE()

SELECT DATENAME(YEAR, GETDATE())

SELECT DATENAME(MICROSECOND, GETDATE())

SELECT DATENAME(WEEKDAY, GETDATE())

SELECT DATEPART(MONTH, GETDATE())

SELECT DAY(GETDATE())

SELECT YEAR(GETDATE())

SELECT DATEFROMPARTS(2020,5,1)

SELECT DATEDIFF(YEAR,DATEFROMPARTS(1955,5,1),GETDATE())

SELECT DATEADD(MONTH,11,GETDATE())

SELECT ISDATE('2018-01-01')

SELECT ISDATE('2018-01-28')

SELECT [DATA DE NASCIMENTO], CONCAT(DATENAME(DAY, [DATA DE NASCIMENTO]), ' de ', DATENAME(MONTH, [DATA DE NASCIMENTO]) ,' de ', DATENAME(YEAR, [DATA DE NASCIMENTO])) AS 'DATA ESCRITA' FROM [dbo].[TABELA DE CLIENTES]

SELECT NOME, DATEDIFF(YEAR,[DATA DE NASCIMENTO],GETDATE()) AS 'IDADE'
FROM [dbo].[TABELA DE CLIENTES]

-- FUNÇÕES MATEMÁTICAS

--CEILING

SELECT CEILING(7.3333332) AS 'ARREDONDA PARA CIMA'

--FLOOR
SELECT FLOOR(7.3333332) AS 'ARREDONDA PARA BAIXO'

-- RAND
SELECT 12 * RAND()

--ROUND
SELECT ROUND(7.33333333,2) 

SELECT[QUANTIDADE],[PREÇO], ROUND([QUANTIDADE]*[PREÇO],1)  FROM [dbo].[TABELA DE ITENS NOTAS FISCAIS]

-- QUANTIDADE DE IMPOSTO PAGO NO ANO 2016, ARREDONDADO PARA MENOR
SELECT YEAR(NF.DATA) AS 'ANO', FORMAT(FLOOR(SUM(INF.[QUANTIDADE]*INF.PREÇO*NF.[IMPOSTO])), '#,###.##','PT-BR') AS 'QUANTIDADE DE IMPOSTO' FROM [dbo].[TABELA DE ITENS NOTAS FISCAIS]INF
INNER JOIN [dbo].[TABELA DE NOTAS FISCAIS] NF
ON NF.NUMERO = INF.NUMERO
WHERE YEAR([DATA])=2016
GROUP BY YEAR(NF.DATA)

-- CONVERSÃO DE DADOS

SELECT CONVERT(VARCHAR,GETDATE(),101) AS 'PADRÃO EUA'

SELECT CONVERT(VARCHAR,GETDATE(),103) AS 'PADRÃO BRITANICO/FRANCES - BR'

-- Queremos construir um SQL cujo resultado seja, para cada cliente: "O cliente JOÃO DA SILVA faturou 12000 no ano de 2016"
SELECT CONCAT('O cliente ', C.NOME, ' faturou ', B.FATURA ,' no ano de 2016' ) AS 'FRASE DE FATURAMENTO' FROM [dbo].[TABELA DE CLIENTES] C
FULL JOIN (SELECT C.NOME, FORMAT(SUM(INF.[QUANTIDADE]*INF.[PREÇO]), '#,###.##','PT-BR') AS 'FATURA'FROM [dbo].[TABELA DE NOTAS FISCAIS] NF
RIGHT JOIN [dbo].[TABELA DE CLIENTES] C ON C.CPF = NF.CPF
INNER JOIN [dbo].[TABELA DE ITENS NOTAS FISCAIS] INF ON INF.NUMERO = NF.NUMERO
WHERE YEAR(NF.DATA)=2016
GROUP BY C.NOME) B
ON C.NOME = B.NOME

