USE ESQUINA_VENDAS
-- HAVING
SELECT BAIRRO,ESTADO, SUM([LIMITE DE CREDITO]) AS 'SOMA DE LIMITE DE CREDITO' FROM [dbo].[TABELA DE CLIENTES]
WHERE ESTADO = 'SP'
GROUP BY BAIRRO, ESTADO

SELECT BAIRRO,ESTADO, SUM([LIMITE DE CREDITO]) AS 'SOMA DE LIMITE DE CREDITO' FROM [dbo].[TABELA DE CLIENTES]
WHERE ESTADO = 'SP'
GROUP BY BAIRRO, ESTADO
HAVING SUM([LIMITE DE CREDITO]) >=140000

SELECT EMBALAGEM, SUM([PRECO DE LISTA]) AS 'SOMA',MAX([PRECO DE LISTA]) AS 'MAX', MIN([PRECO DE LISTA]) AS 'MIN' FROM [dbo].[TABELA DE PRODUTOS]
GROUP BY EMBALAGEM
HAVING SUM([PRECO DE LISTA])<80 AND MAX([PRECO DE LISTA])>6

SELECT EMBALAGEM, SUM([PRECO DE LISTA]) AS 'SOMA',MAX([PRECO DE LISTA]) AS 'MAX', MIN([PRECO DE LISTA]) AS 'MIN' FROM [dbo].[TABELA DE PRODUTOS]
GROUP BY EMBALAGEM
HAVING NOT(SUM([PRECO DE LISTA])<80 AND MAX([PRECO DE LISTA])>6)

-- QUAIS SÃO OS CLIENTES QUE FIZERAM MAIS DE 2000 COMPRAS EM 2016
SELECT CPF, COUNT([NUMERO]) AS 'QUANTIDADE DE COMPRAS',MAX([DATA]) AS 'ULTIMA COMPRA EM 2016', MIN([DATA]) AS 'PRIMEIRA COMPRA EM 2016'  FROM [dbo].[TABELA DE NOTAS FISCAIS]
WHERE YEAR([DATA]) = '2016'
GROUP BY CPF
HAVING COUNT([NUMERO])>2000
ORDER BY COUNT([NUMERO])
-- END

-- CASE

SELECT [NOME DO PRODUTO],
	CASE
		WHEN [PRECO DE LISTA] >=12 THEN 'PRODUTO CARO'
		WHEN [PRECO DE LISTA] >=7 THEN 'PRODUTO EM CONTA'
		ELSE 'PRODUTO BARATO'
	END AS 'CLASSIFICAÇÃO DE PREÇO'
FROM [dbo].[TABELA DE PRODUTOS]
ORDER BY [PRECO DE LISTA]


SELECT [NOME DO PRODUTO],
	CASE
		WHEN [PRECO DE LISTA] >=12 THEN 'PRODUTO CARO'
		WHEN [PRECO DE LISTA] >=7 THEN 'PRODUTO EM CONTA'
		ELSE 'PRODUTO BARATO'
	END AS 'CLASSIFICAÇÃO DE PREÇO', AVG([PRECO DE LISTA]) AS 'MÉDIA'
FROM [dbo].[TABELA DE PRODUTOS]
GROUP BY [NOME DO PRODUTO],
CASE
		WHEN [PRECO DE LISTA] >=12 THEN 'PRODUTO CARO'
		WHEN [PRECO DE LISTA] >=7 THEN 'PRODUTO EM CONTA'
		ELSE 'PRODUTO BARATO'
END
ORDER BY 
CASE
		WHEN [PRECO DE LISTA] >=12 THEN 'PRODUTO CARO'
		WHEN [PRECO DE LISTA] >=7 THEN 'PRODUTO EM CONTA'
		ELSE 'PRODUTO BARATO'
END


SELECT [NOME], YEAR([DATA DE NASCIMENTO]) AS 'ANO DE NASCIMENTO',
CASE
	WHEN YEAR([DATA DE NASCIMENTO])<1990 THEN 'ADULTO'
	WHEN YEAR([DATA DE NASCIMENTO])<=1995 THEN 'JOVENS'
	ELSE 'CRIANÇA'
END AS 'CLASSIFICAÇÃO IDADE'
FROM [dbo].[TABELA DE CLIENTES]
ORDER BY YEAR([DATA DE NASCIMENTO]) DESC

--END

-- JOIN

SELECT C.[NOME], N.[MATRICULA] FROM [dbo].[TABELA DE CLIENTES] C
INNER JOIN [dbo].[TABELA DE NOTAS FISCAIS] N
ON C.[CPF] = N.[CPF]

SELECT * FROM [dbo].[TABELA DE VENDEDORES] V
INNER JOIN [dbo].[TABELA DE NOTAS FISCAIS] NF
ON V.MATRICULA = NF.MATRICULA

SELECT V.[NOME] AS 'NOME DO VENDEDOR',V.[MATRICULA], NF.[DATA] AS 'DATA DA COMPRA', NF.[CPF] AS 'CPF DO CLIENTE'  FROM [dbo].[TABELA DE VENDEDORES] V
INNER JOIN [dbo].[TABELA DE NOTAS FISCAIS] NF
ON V.MATRICULA = NF.MATRICULA

SELECT V.MATRICULA, V.NOME, COUNT(*) AS 'NOTA FISCAL POR VENDEDOR' FROM [dbo].[TABELA DE VENDEDORES] V
INNER JOIN [dbo].[TABELA DE NOTAS FISCAIS] NF
ON V.MATRICULA = NF.MATRICULA
GROUP BY V.MATRICULA, V.NOME