USE ESQUINA_VENDAS
-- 
SELECT B.NOME ,B.[ANO/MÊS],B.[QUANTIDADE MÊS], B.[VOLUME DE COMPRA],
	CASE
		WHEN B.[QUANTIDADE MÊS] > B.[VOLUME DE COMPRA] THEN 'VENDA INVÁLIDA' 
		ELSE 'VENDA VÁLIDA'
	END AS 'CLASSIFICAÇÃO'
FROM
(SELECT C.NOME, A.[ANO/MÊS], A.[QUANTIDADE MÊS], C.[VOLUME DE COMPRA] FROM [dbo].[TABELA DE CLIENTES] C
INNER JOIN
(SELECT NF.CPF, SUBSTRING(CONVERT(VARCHAR, NF.DATA,120),1,7) AS 'ANO/MÊS', SUM(INF.QUANTIDADE) AS 'QUANTIDADE MÊS' FROM [dbo].[TABELA DE NOTAS FISCAIS]NF
INNER JOIN [dbo].[TABELA DE ITENS NOTAS FISCAIS]INF
ON NF.NUMERO = INF.NUMERO	
GROUP BY NF.CPF, SUBSTRING(CONVERT(VARCHAR, NF.DATA,120),1,7)) A
ON C.CPF = A.CPF) B
ORDER BY B.NOME, B.[ANO/MÊS]


-- O dono da Esquina do Sucos pediu para que criasse um relatório mostrando qual foi o faturamento em dinheiro por sabor de produto e também que comparasse a participação daquela venda em relação ao total (%). Somente do ano 2016

CREATE VIEW TODOS_CAMPOS AS
SELECT P.SABOR, P.[CODIGO DO PRODUTO], INF.PREÇO, INF.QUANTIDADE, NF.DATA, NF.NUMERO FROM [dbo].[TABELA DE ITENS NOTAS FISCAIS]INF
INNER JOIN [dbo].[TABELA DE PRODUTOS] P ON INF.[CODIGO DO PRODUTO] = P.[CODIGO DO PRODUTO]
INNER JOIN [dbo].[TABELA DE NOTAS FISCAIS]NF ON INF.NUMERO = NF.NUMERO

CREATE VIEW FATURAMENTO AS
SELECT SABOR, YEAR(DATA) AS 'ANO',ROUND( SUM(QUANTIDADE*PREÇO),2) AS 'FATURAMENTO' FROM TODOS_CAMPOS
WHERE YEAR(DATA) = 2016
GROUP BY SABOR, YEAR(DATA)

CREATE VIEW FATURAMENTO_TOTAL AS
SELECT ANO, SUM(FATURAMENTO) AS 'FATURAMENTO TOTAL' FROM FATURAMENTO
GROUP BY ANO

SELECT F.SABOR, F.ANO, F.FATURAMENTO, CONCAT(ROUND((F.FATURAMENTO*100/FT.[FATURAMENTO TOTAL]),2),' %' )AS 'PARTICIPAÇÃO' FROM FATURAMENTO F
INNER JOIN FATURAMENTO_TOTAL FT
ON F.ANO = FT.ANO
ORDER BY F.FATURAMENTO DESC
