CREATE DATABASE  [ESQUINA_VENDAS]

-------------------------------------------------
USE [ESQUINA_VENDAS]

CREATE TABLE [TABELA DE PRODUTOS](
    [CODIGO DO PRODUTO] [VARCHAR](10),
    [NOME DO PRODUTO][VARCHAR](50),
    [EMBALAGEM][VARCHAR](20),
    [TAMANHO][VARCHAR](10),
    [SABOR][VARCHAR](20),
    [PRECO DE LISTA][SMALLMONEY],
    
)

--------------------------------------------------

USE [ESQUINA_VENDAS]

CREATE TABLE [TABELA DE CLIENTES]
( [CPF] [VARCHAR] (11) ,
[NOME] [VARCHAR] (100) ,
[ENDERECO] [VARCHAR] (150) ,
[COMPLEMENTO] [VARCHAR] (150) ,
[BAIRRO] [VARCHAR] (50) ,
[CIDADE] [VARCHAR] (50) ,
[ESTADO] [VARCHAR] (2) ,
[CEP] [VARCHAR] (8) ,
[DATA DE NASCIMENTO] [DATE],
[IDADE] [SMALLINT],
[SEXO] [VARCHAR] (1) ,
[LIMITE DE CREDITO] [MONEY] ,
[VOLUME DE COMPRA] [FLOAT] ,
[PRIMEIRA COMPRA] [BIT] )

-------------------------------------------------

USE [ESQUINA_VENDAS]

CREATE TABLE [TABELA DE VENDEDORES]
( [MATRICULA] varchar(5),
[NOME] varchar(100),
[PERCENTUAL COMISSAO] float)

-------------------------------------------------




--------------------Inserts-----------------------

--INSERINDO REGISTROS NA TABELA DE VENDEDORES
USE [ESQUINA_VENDAS]


INSERT INTO [TABELA DE VENDEDORES]
([MATRICULA], [NOME], [PERCENTUAL COMISSAO])
VALUES
('00122','Joabe da Silva Freitas',0.10)

INSERT INTO [TABELA DE VENDEDORES]
([MATRICULA], [NOME], [PERCENTUAL COMISSAO])
VALUES
('00133','Marly dos Santos Gama',0.8)

INSERT INTO [TABELA DE VENDEDORES]
([MATRICULA], [NOME], [PERCENTUAL COMISSAO])
VALUES
('00144','Bruno César Brandão',0.5)

INSERT INTO [TABELA DE VENDEDORES]
([MATRICULA], [NOME], [PERCENTUAL COMISSAO])
VALUES
('00155','Roberta Martins',0.11)

INSERT INTO [TABELA DE VENDEDORES]
([MATRICULA], [NOME], [PERCENTUAL COMISSAO])
VALUES
('00166','Pericles Alves',0.07)

-------------------------------------------------------

--INSERINDO REGISTROS NA TABELA DE PRODUTOS

USE [ESQUINA_VENDAS]

INSERT INTO [TABELA DE PRODUTOS]
([CODIGO DO PRODUTO],[NOME DO PRODUTO],[EMBALAGEM],[TAMANHO],[SABOR], [PRECO DE LISTA])
  VALUES 
  ('1040107','Light - 350 ml - Melancia','Lata','350 ml','Melancia',4.56),
   ('1037797','Clean - 2 Litros - Laranja','PET','2 Litros','Laranja',16.01),
    ('1000889','Sabor da Montanha - 700 ml - Uva','Garrafa','700 ml','Uva',6.31),
     ('1004327','Videira do Campo - 1,5 Litros - Melancia','PET','1,5 Litros','Melancia',19.51),
      ('1088126','Linha Citros - 1 Litro - Limão','PET','1 Litro','Limão',7.00),
       ('544931','Frescor do Verão - 350 ml - Limão','Lata','350 ml','Limão',2.46),
        ('1078680','Frescor do Verão - 470 ml - Manga','Garrafa','470 ml','Manga',5.18)







--------------------------------------- Aula 5 – Chave Primária e manipulando outros tipos de dados -----------------------------------------


INSERT INTO [TABELA DE PRODUTOS]([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA])
VALUES('788975', 'Pedaços de Frutas - 1,5 Litros - Maça', 'PET', '1,5 Litros', 'Maça', 18.01)

INSERT INTO [TABELA DE PRODUTOS]([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA])
VALUES('788975', 'Pedaços de Frutas - 1,5 Litros - Maça', 'PET', '1,5 Litros', 'Maça', 18.01)



DROP TABLE [TABELA DE PRODUTOS]


CREATE TABLE [TABELA DE PRODUTOS](
    [CODIGO DO PRODUTO] [VARCHAR](10),
    [NOME DO PRODUTO][VARCHAR](50),
    [EMBALAGEM][VARCHAR](20),
    [TAMANHO][VARCHAR](10),
    [SABOR][VARCHAR](20),
    [PREÇO DE LISTA][SMALLMONEY],
    PRIMARY KEY  ([CODIGO DO PRODUTO])
    
)


--INSERINDO REGISTROS NA TABELA DE PRODUTOS

USE [ESQUINA_VENDAS]

INSERT INTO [TABELA DE PRODUTOS]
([CODIGO DO PRODUTO],[NOME DO PRODUTO],[EMBALAGEM],[TAMANHO],[SABOR], [PRECO DE LISTA])
  VALUES 
  ('1040107','Light - 350 ml - Melancia','Lata','350 ml','Melancia',4.56),
  ('1037797','Clean - 2 Litros - Laranja','PET','2 Litros','Laranja',16.01),
  ('1000889','Sabor da Montanha - 700 ml - Uva','Garrafa','700 ml','Uva',6.31),
  ('1004327','Videira do Campo - 1,5 Litros - Melancia','PET','1,5 Litros','Melancia',19.51),
  ('1088126','Linha Citros - 1 Litro - Limão','PET','1 Litro','Limão',7.00),
  ('544931','Frescor do Verão - 350 ml - Limão','Lata','350 ml','Limão',2.46),
  ('1078680','Frescor do Verão - 470 ml - Manga','Garrafa','470 ml','Manga',5.18)




INSERT INTO [TABELA DE PRODUTOS]([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PREÇO DE LISTA])
VALUES('788975', 'Pedaços de Frutas - 1,5 Litros - Maça', 'PET', '1,5 Litros', 'Maça', 18.01)

-------------------------------- DESAFIO 1 DA AULA 5 ----------------------------------------------------------

DROP TABLE [TABELA DE CLIENTES]

CREATE TABLE [TABELA DE CLIENTES]
( [CPF] [VARCHAR] (11) ,
[NOME] [VARCHAR] (100) ,
[ENDERECO] [VARCHAR] (150) ,
[COMPLEMENTO] [VARCHAR] (150) ,
[BAIRRO] [VARCHAR] (50) ,
[CIDADE] [VARCHAR] (50) ,
[ESTADO] [VARCHAR] (2) ,
[CEP] [VARCHAR] (8) ,
[DATA DE NASCIMENTO] [DATE],
[IDADE] [SMALLINT],
[SEXO] [VARCHAR] (1) ,
[LIMITE DE CREDITO] [MONEY] ,
[VOLUME DE COMPRA] [FLOAT] ,
[PRIMEIRA COMPRA] [BIT],
PRIMARY KEY ([CPF])
)



---------------- DESAFIO 2 (MASTER) DA AULA 5 -------------------------------------

DROP TABLE [TABELA DE VENDEDORES]



CREATE TABLE [TABELA DE VENDEDORES]
( [MATRICULA] [VARCHAR](5),
[NOME] [VARCHAR](100),
[PERCENTUAL COMISSAO] [FLOAT],
[DATA DE ADMISSAO][DATE],
[FERIAS][BIT]
PRIMARY KEY ([MATRICULA])
)


INSERT INTO [TABELA DE VENDEDORES]
([MATRICULA], [NOME], [PERCENTUAL COMISSAO],[DATA DE ADMISSAO],[FERIAS])
VALUES
('00133','Marly dos Santos Gama',0.08,'15/08/2014',0)

INSERT INTO [TABELA DE VENDEDORES]
([MATRICULA], [NOME], [PERCENTUAL COMISSAO],[DATA DE ADMISSAO],[FERIAS])
VALUES
('00144','Bruno César Brandão',0.05,'15/08/2016',1)

INSERT INTO [TABELA DE VENDEDORES]
([MATRICULA], [NOME], [PERCENTUAL COMISSAO],[DATA DE ADMISSAO],[FERIAS])
VALUES
('00155','Roberta Serra',0.11,'15/08/2018',0)

INSERT INTO [TABELA DE VENDEDORES]
([MATRICULA], [NOME], [PERCENTUAL COMISSAO],[DATA DE ADMISSAO],[FERIAS])
VALUES
('00166','Pericles Alves',0.11,'15/08/2019',1)



INSERT INTO [TABELA DE CLIENTES] 
(	[CPF],
	[NOME],
	[ENDERECO],
	[COMPLEMENTO],
	[BAIRRO],
	[CIDADE],
	[ESTADO],
	[CEP],
	[DATA DE NASCIMENTO],
	[IDADE],
	[SEXO],
	[LIMITE DE CREDITO],
	[VOLUME DE COMPRA],
	[PRIMEIRA COMPRA]) 
VALUES 
(	
	'51073366200',
	'Márcio Ladislau Freitas',
	'R. Dois de Fevereiro',
	'',
	'Água Santa',
	'Rio de Janeiro',
	'RJ',
	'22000000',
	--'2000-02-12',
	'12/31/2000',
	18,
	'M',
	100000,
	200000,
	1
)



  DELETE FROM [TABELA DE CLIENTES]
  WHERE [CPF] = '51073366200'



------------------------------------------------------Aula 06 ------------------------------------------------


USE [ESQUINA_VENDAS]

DROP TABLE [TABELA DE CLIENTES]

CREATE TABLE [TABELA DE CLIENTES](
	[CPF] [VARCHAR](11) ,
	[NOME] [VARCHAR](100) ,
	[ENDERECO] [VARCHAR](150) ,
	[COMPLEMENTO] [VARCHAR](150) ,
	[BAIRRO] [VARCHAR](50) ,
	[CIDADE] [VARCHAR](50) ,
	[ESTADO] [VARCHAR](2) ,
	[CEP] [VARCHAR](8) ,
	[DATA DE NASCIMENTO] [DATE] ,
	[IDADE] [SMALLINT ] ,
	[SEXO] [VARCHAR](1) ,
	[LIMITE DE CREDITO] [MONEY] ,
	[VOLUME DE COMPRA] [FLOAT] ,
	[PRIMEIRA COMPRA] [BIT] ,
 	PRIMARY KEY ([CPF])
)


INSERT INTO [TABELA DE CLIENTES] ([CPF],[NOME],[ENDERECO],[COMPLEMENTO],[BAIRRO],[CIDADE],[ESTADO],[CEP],[DATA DE NASCIMENTO],[IDADE],[SEXO],[LIMITE DE CREDITO],[VOLUME DE COMPRA],[PRIMEIRA COMPRA]) VALUES ('19290992743','Fernando Cavalcante','R. Dois de Fevereiro','','Água Santa','Rio de Janeiro','RJ','22000000','2000-02-12',18,'M',100000,200000,1)
INSERT INTO [TABELA DE CLIENTES] ([CPF],[NOME],[ENDERECO],[COMPLEMENTO],[BAIRRO],[CIDADE],[ESTADO],[CEP],[DATA DE NASCIMENTO],[IDADE],[SEXO],[LIMITE DE CREDITO],[VOLUME DE COMPRA],[PRIMEIRA COMPRA]) VALUES ('2600586709','César Teixeira','Rua Conde de Bonfim','','Tijuca','Rio de Janeiro','RJ','22020001','2000-03-12',18,'M',120000,220000,0)
INSERT INTO [TABELA DE CLIENTES] ([CPF],[NOME],[ENDERECO],[COMPLEMENTO],[BAIRRO],[CIDADE],[ESTADO],[CEP],[DATA DE NASCIMENTO],[IDADE],[SEXO],[LIMITE DE CREDITO],[VOLUME DE COMPRA],[PRIMEIRA COMPRA]) VALUES ('95939180787','Fábio Carvalho','R. dos Jacarandás da Península','','Barra da Tijuca','Rio de Janeiro','RJ','22002020','1992-01-05',16,'M',90000,180000,1)
INSERT INTO [TABELA DE CLIENTES] ([CPF],[NOME],[ENDERECO],[COMPLEMENTO],[BAIRRO],[CIDADE],[ESTADO],[CEP],[DATA DE NASCIMENTO],[IDADE],[SEXO],[LIMITE DE CREDITO],[VOLUME DE COMPRA],[PRIMEIRA COMPRA]) VALUES ('9283760794','Edson Meilelles','R. Pinto de Azevedo','','Cidade Nova','Rio de Janeiro','RJ','22002002','1995-10-07',22,'M',150000,250000,1)
INSERT INTO [TABELA DE CLIENTES] ([CPF],[NOME],[ENDERECO],[COMPLEMENTO],[BAIRRO],[CIDADE],[ESTADO],[CEP],[DATA DE NASCIMENTO],[IDADE],[SEXO],[LIMITE DE CREDITO],[VOLUME DE COMPRA],[PRIMEIRA COMPRA]) VALUES ('7771579779','Marcelo Mattos','R. Eduardo Luís Lopes','','Brás','São Paulo','SP','88202912','1992-03-25',25,'M',120000,200000,1)
INSERT INTO [TABELA DE CLIENTES] ([CPF],[NOME],[ENDERECO],[COMPLEMENTO],[BAIRRO],[CIDADE],[ESTADO],[CEP],[DATA DE NASCIMENTO],[IDADE],[SEXO],[LIMITE DE CREDITO],[VOLUME DE COMPRA],[PRIMEIRA COMPRA]) VALUES ('5576228758','Petra Oliveira','R. Benício de Abreu','','Lapa','São Paulo','SP','88192029','1995-11-14',22,'F',70000,160000,1)
INSERT INTO [TABELA DE CLIENTES] ([CPF],[NOME],[ENDERECO],[COMPLEMENTO],[BAIRRO],[CIDADE],[ESTADO],[CEP],[DATA DE NASCIMENTO],[IDADE],[SEXO],[LIMITE DE CREDITO],[VOLUME DE COMPRA],[PRIMEIRA COMPRA]) VALUES ('8502682733','Valdeci da Silva','R. Srg. Édison de Oliveira','','Jardins','São Paulo','SP','82122020','1995-10-07',22,'M',110000,190000,0)
INSERT INTO [TABELA DE CLIENTES] ([CPF],[NOME],[ENDERECO],[COMPLEMENTO],[BAIRRO],[CIDADE],[ESTADO],[CEP],[DATA DE NASCIMENTO],[IDADE],[SEXO],[LIMITE DE CREDITO],[VOLUME DE COMPRA],[PRIMEIRA COMPRA]) VALUES ('1471156710','Érica Carvalho','R. Iriquitia','','Jardins','São Paulo','SP','80012212','1990-09-01',27,'F',170000,245000,0)
INSERT INTO [TABELA DE CLIENTES] ([CPF],[NOME],[ENDERECO],[COMPLEMENTO],[BAIRRO],[CIDADE],[ESTADO],[CEP],[DATA DE NASCIMENTO],[IDADE],[SEXO],[LIMITE DE CREDITO],[VOLUME DE COMPRA],[PRIMEIRA COMPRA]) VALUES ('3623344710','Marcos Nougeuira','Av. Pastor Martin Luther King Junior','','Inhauma','Rio de Janeiro','RJ','22002012','1995-01-13',23,'M',110000,220000,1)
INSERT INTO [TABELA DE CLIENTES] ([CPF],[NOME],[ENDERECO],[COMPLEMENTO],[BAIRRO],[CIDADE],[ESTADO],[CEP],[DATA DE NASCIMENTO],[IDADE],[SEXO],[LIMITE DE CREDITO],[VOLUME DE COMPRA],[PRIMEIRA COMPRA]) VALUES ('50534475787','Abel Silva ','Rua Humaitá','','Humaitá','Rio de Janeiro','RJ','22000212','1995-09-11',22,'M',170000,260000,0)
INSERT INTO [TABELA DE CLIENTES] ([CPF],[NOME],[ENDERECO],[COMPLEMENTO],[BAIRRO],[CIDADE],[ESTADO],[CEP],[DATA DE NASCIMENTO],[IDADE],[SEXO],[LIMITE DE CREDITO],[VOLUME DE COMPRA],[PRIMEIRA COMPRA]) VALUES ('5840119709','Gabriel Araujo','R. Manuel de Oliveira','','Santo Amaro','São Paulo','SP','80010221','1985-03-16',32,'M',140000,210000,1)
INSERT INTO [TABELA DE CLIENTES] ([CPF],[NOME],[ENDERECO],[COMPLEMENTO],[BAIRRO],[CIDADE],[ESTADO],[CEP],[DATA DE NASCIMENTO],[IDADE],[SEXO],[LIMITE DE CREDITO],[VOLUME DE COMPRA],[PRIMEIRA COMPRA]) VALUES ('94387575700','Walber Lontra','R. Cel. Almeida','','Piedade','Rio de Janeiro','RJ','22000201','1989-06-20',28,'M',60000,120000,1)
INSERT INTO [TABELA DE CLIENTES] ([CPF],[NOME],[ENDERECO],[COMPLEMENTO],[BAIRRO],[CIDADE],[ESTADO],[CEP],[DATA DE NASCIMENTO],[IDADE],[SEXO],[LIMITE DE CREDITO],[VOLUME DE COMPRA],[PRIMEIRA COMPRA]) VALUES ('8719655770','Carlos Eduardo','Av. Gen. Guedes da Fontoura','','Jardins','São Paulo','SP','81192002','1983-12-20',34,'M',200000,240000,0)
INSERT INTO [TABELA DE CLIENTES] ([CPF],[NOME],[ENDERECO],[COMPLEMENTO],[BAIRRO],[CIDADE],[ESTADO],[CEP],[DATA DE NASCIMENTO],[IDADE],[SEXO],[LIMITE DE CREDITO],[VOLUME DE COMPRA],[PRIMEIRA COMPRA]) VALUES ('5648641702','Paulo César Mattos','Rua Hélio Beltrão','','Tijuca','Rio de Janeiro','RJ','21002020','1991-08-30',26,'M',120000,220000,0)
INSERT INTO [TABELA DE CLIENTES] ([CPF],[NOME],[ENDERECO],[COMPLEMENTO],[BAIRRO],[CIDADE],[ESTADO],[CEP],[DATA DE NASCIMENTO],[IDADE],[SEXO],[LIMITE DE CREDITO],[VOLUME DE COMPRA],[PRIMEIRA COMPRA]) VALUES ('492472718','Eduardo Jorge','R. Volta Grande','','Tijuca','Rio de Janeiro','RJ','22012002','1994-07-19',23,'M',75000,95000,1)

DROP TABLE [TABELA DE PRODUTOS]

CREATE TABLE [TABELA DE PRODUTOS](
	[CODIGO DO PRODUTO] [VARCHAR](10),
	[NOME DO PRODUTO] [VARCHAR](50),
	[EMBALAGEM] [VARCHAR](20),
	[TAMANHO] [VARCHAR](10),
	[SABOR] [VARCHAR](20),
	[PRECO DE LISTA] [SMALLMONEY],
	PRIMARY KEY ([CODIGO DO PRODUTO])
)


INSERT INTO [TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES ('1040107','Light - 350 ml - Melancia','Lata','350 ml','Melancia',4.555)
INSERT INTO [TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES ('1037797','Clean - 2 Litros - Laranja','PET','2 Litros','Laranja',16.008)
INSERT INTO [TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES ('1000889','Sabor da Montanha - 700 ml - Uva','Garrafa','700 ml','Uva',6.309)
INSERT INTO [TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES ('1004327','Videira do Campo - 1,5 Litros - Melancia','PET','1,5 Litros','Melancia',19.51)
INSERT INTO [TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES ('1088126','Linha Citros - 1 Litro - Limão','PET','1 Litro','Limão',7.004)
INSERT INTO [TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES ('544931','Frescor do Verão - 350 ml - Limão','Lata','350 ml','Limão',2.4595)
INSERT INTO [TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES ('1078680','Frescor do Verão - 470 ml - Manga','Garrafa','470 ml','Manga',5.1795)
INSERT INTO [TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES ('1042712','Linha Citros - 700 ml - Limão','Garrafa','700 ml','Limão',4.904)
INSERT INTO [TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES ('788975','Pedaços de Frutas - 1,5 Litros - Maça','PET','1,5 Litros','Maça',18.011)
INSERT INTO [TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES ('1002767','Videira do Campo - 700 ml - Cereja/Maça','Garrafa','700 ml','Cereja/Maça',8.41)
INSERT INTO [TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES ('231776','Festival de Sabores - 700 ml - Açai','Garrafa','700 ml','Açai',13.312)
INSERT INTO [TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES ('479745','Clean - 470 ml - Laranja','Garrafa','470 ml','Laranja',3.768)
INSERT INTO [TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES ('1051518','Frescor do Verão - 470 ml - Limão','Garrafa','470 ml','Limão',3.2995)
INSERT INTO [TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES ('1101035','Linha Refrescante - 1 Litro - Morango/Limão','PET','1 Litro','Morango/Limão',9.0105)
INSERT INTO [TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES ('229900','Pedaços de Frutas - 350 ml - Maça','Lata','350 ml','Maça',4.211)
INSERT INTO [TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES ('1086543','Linha Refrescante - 1 Litro - Manga','PET','1 Litro','Manga',11.0105)
INSERT INTO [TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES ('695594','Festival de Sabores - 1,5 Litros - Açai','PET','1,5 Litros','Açai',28.512)
INSERT INTO [TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES ('838819','Clean - 1,5 Litros - Laranja','PET','1,5 Litros','Laranja',12.008)
INSERT INTO [TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES ('326779','Linha Refrescante - 1,5 Litros - Manga','PET','1,5 Litros','Manga',16.5105)
INSERT INTO [TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES ('520380','Pedaços de Frutas - 1 Litro - Maça','PET','1 Litro','Maça',12.011)
INSERT INTO [TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES ('1041119','Linha Citros - 700 ml - Lima/Limão','Garrafa','700 ml','Lima/Limão',4.904)
INSERT INTO [TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES ('243083','Festival de Sabores - 1,5 Litros - Maracujá','PET','1,5 Litros','Maracujá',10.512)
INSERT INTO [TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES ('394479','Sabor da Montanha - 700 ml - Cereja','Garrafa','700 ml','Cereja',8.409)
INSERT INTO [TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES ('746596','Light - 1,5 Litros - Melancia','PET','1,5 Litros','Melancia',19.505)
INSERT INTO [TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES ('773912','Clean - 1 Litro - Laranja','PET','1 Litro','Laranja',8.008)
INSERT INTO [TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES ('826490','Linha Refrescante - 700 ml - Morango/Limão','Garrafa','700 ml','Morango/Limão',6.3105)
INSERT INTO [TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES ('723457','Festival de Sabores - 700 ml - Maracujá','Garrafa','700 ml','Maracujá',4.912)
INSERT INTO [TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES ('812829','Clean - 350 ml - Laranja','Lata','350 ml','Laranja',2.808)
INSERT INTO [TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES ('290478','Videira do Campo - 350 ml - Melancia','Lata','350 ml','Melancia',4.56)
INSERT INTO [TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES ('783663','Sabor da Montanha - 700 ml - Morango','Garrafa','700 ml','Morango',7.709)
INSERT INTO [TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES ('235653','Frescor do Verão - 350 ml - Manga','Lata','350 ml','Manga',3.8595)
INSERT INTO [TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES ('1002334','Linha Citros - 1 Litro - Lima/Limão','PET','1 Litro','Lima/Limão',7.004)
INSERT INTO [TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES ('1013793','Videira do Campo - 2 Litros - Cereja/Maça','PET','2 Litros','Cereja/Maça',24.01)
INSERT INTO [TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES ('1096818','Linha Refrescante - 700 ml - Manga','Garrafa','700 ml','Manga',7.7105)
INSERT INTO [TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES ('1022450','Festival de Sabores - 2 Litros - Açai','PET','2 Litros','Açai',38.012)



DROP TABLE [TABELA DE VENDEDORES]



CREATE TABLE [TABELA DE VENDEDORES]
( [MATRICULA] [VARCHAR](5),
[NOME] [VARCHAR](100),
[PERCENTUAL COMISSAO] [FLOAT],
[DATA DE ADMISSAO][DATE],
[FERIAS][BIT]
PRIMARY KEY ([MATRICULA])

)


INSERT INTO [TABELA DE VENDEDORES]
([MATRICULA], [NOME], [PERCENTUAL COMISSAO],[DATA DE ADMISSAO],[FERIAS])
VALUES
('00133','Marly dos Santos Gama',0.08,'15/08/2014',0)

INSERT INTO [TABELA DE VENDEDORES]
([MATRICULA], [NOME], [PERCENTUAL COMISSAO],[DATA DE ADMISSAO],[FERIAS])
VALUES
('00144','Bruno César Brandão',0.05,'15/08/2016',1)

INSERT INTO [TABELA DE VENDEDORES]
([MATRICULA], [NOME], [PERCENTUAL COMISSAO],[DATA DE ADMISSAO],[FERIAS])
VALUES
('00155','Roberta Serra',0.11,'15/08/2018',0)

INSERT INTO [TABELA DE VENDEDORES]
([MATRICULA], [NOME], [PERCENTUAL COMISSAO],[DATA DE ADMISSAO],[FERIAS])
VALUES
('00166','Pericles Alves',0.11,'15/08/2019',1)

--------------------FILTRANDO REGISTROS-------------------------

SELECT * FROM [TABELA DE PRODUTOS]

DELETE FROM [TABELA DE PRODUTOS] 
WHERE [CODIGO DO PRODUTO] = '1000889'



SELECT * FROM [TABELA DE PRODUTOS] 
WHERE [CODIGO DO PRODUTO] = '1000889'

SELECT * FROM [TABELA DE PRODUTOS] 
WHERE [SABOR] = 'Uva'

SELECT * FROM [TABELA DE PRODUTOS] 
WHERE [SABOR] = 'Limão'

DELETE FROM [TABELA DE PRODUTOS] 
WHERE [SABOR] = 'Limão'



---------------------- 1 DESAFIO DA AULA 6 --------------------------------------



SELECT [NOME], [MATRICULA] FROM [TABELA DE VENDEDORES]

SELECT [NOME DO PRODUTO] AS 'DESCRIÇÃO DO PRODUTO', [CODIGO DO PRODUTO] AS 'IDENTIFICADOR', [PRECO DE LISTA] AS 'PREÇO A PAGAR'
FROM [TABELA DE PRODUTOS]

SELECT TOP (7) [NOME],[CPF],[CIDADE] FROM [TABELA DE CLIENTES]

---------------------- 2 DESAFIO DA AULA 6 -------------------------------------

SELECT * FROM [TABELA DE VENDEDORES]
WHERE [NOME] = 'Roberta Serra'



------------------FILTRANDO REGISTROS MAIOR,MENOR,DIFERENTE----------------------


SELECT * FROM [TABELA DE PRODUTOS]

SELECT * FROM [TABELA DE PRODUTOS] WHERE EMBALAGEM = 'PET'

SELECT * FROM [TABELA DE PRODUTOS] WHERE [PREÇO DE LISTA] = 4.555

SELECT * FROM [TABELA DE PRODUTOS] WHERE [PREÇO DE LISTA] > 10

SELECT * FROM [TABELA DE PRODUTOS] WHERE [PREÇO DE LISTA] < 10

SELECT * FROM [TABELA DE PRODUTOS] WHERE [PREÇO DE LISTA] <= 4.555

SELECT * FROM [TABELA DE PRODUTOS] WHERE [PREÇO DE LISTA] >= 4.555

SELECT * FROM [TABELA DE PRODUTOS] WHERE EMBALAGEM <= 'Lata'

SELECT * FROM [TABELA DE PRODUTOS] WHERE EMBALAGEM <> 'Lata'

SELECT * FROM [TABELA DE PRODUTOS] WHERE [PREÇO DE LISTA] <> 4.555


------------------------- 3 DESAFIO DA AULA 6 -----------------------------------



SELECT * FROM [TABELA DE VENDEDORES] WHERE [PERCENTUAL COMISSAO] > 0.10



-----------------------FILTRANDO POR DATAS----------------------------------------

SELECT * FROM [TABELA DE CLIENTES]

SELECT * FROM [TABELA DE CLIENTES] WHERE [DATA DE NASCIMENTO] = '1995-09-11'

SELECT * FROM [TABELA DE CLIENTES] WHERE [DATA DE NASCIMENTO] >= '1995-09-11'

SELECT * FROM [TABELA DE CLIENTES] WHERE [DATA DE NASCIMENTO] <= '1995-09-11'

SELECT * FROM [TABELA DE CLIENTES]
WHERE [DATA DE NASCIMENTO] >= '1995-01-01' AND [DATA DE NASCIMENTO]<='1995-12-31'


SELECT * FROM [TABELA DE CLIENTES] WHERE YEAR([DATA DE NASCIMENTO]) = 1995 

SELECT * FROM [TABELA DE CLIENTES] WHERE YEAR([DATA DE NASCIMENTO]) < 1995 

SELECT * FROM [TABELA DE CLIENTES] WHERE MONTH([DATA DE NASCIMENTO]) = 12

SELECT * FROM [TABELA DE CLIENTES] WHERE DAY([DATA DE NASCIMENTO]) = 11


SELECT MONTH([DATA DE NASCIMENTO]) AS 'MES' FROM [TABELA DE CLIENTES]
WHERE YEAR ([DATA DE NASCIMENTO]) = 1995

SELECT [NOME] AS 'NOME DO CLIENTE',YEAR([DATA DE NASCIMENTO]) AS 'ANO' ,MONTH([DATA DE NASCIMENTO]) AS 'MES'  FROM [TABELA DE CLIENTES]
WHERE YEAR ([DATA DE NASCIMENTO]) = 1995

---------------------------AQUI PRA VOCÊS A CHAVE ESTRANGEIRA QUANDO FIZ O TESTE ------------------------------------------------------
 

CREATE TABLE TESTE
(
    [MATRICULA TESTE][VARCHAR] (10),
    [NOME TESTE][VARCHAR](255),
	[MARCA TESTE][VARCHAR](255),
	PRIMARY KEY ([MATRICULA TESTE]),
    
	[MATRICULA][VARCHAR](5) NOT NULL,
	FOREIGN KEY ([MATRICULA])  REFERENCES [TABELA DE VENDEDORES] ([MATRICULA])
	
)

-- NAO PODE INSERIR VALOR NULO PORQUE É CHAVE ESTRANGEIRA (APENAS TESTE)
INSERT INTO [TESTE] ([MATRICULA TESTE],[NOME TESTE],[MARCA TESTE])
VALUES ('0001','TESTE CARRO','TESTE MARCA')

-- AQUI FOI TESTADO UM VALOR DE MATRICULA QUE NÃO SE ENCONTRA NA TABELA DE VENDEDORES (APENAS TESTE)
INSERT INTO [TESTE] ([MATRICULA TESTE],[NOME TESTE],[MARCA TESTE],[MATRICULA])
VALUES ('0001','TESTE CARRO','TESTE MARCA','00199')

-- INSERINDO VALORES CORRETOS  :) (APENAS TESTE)---
INSERT INTO [TESTE] ([MATRICULA TESTE],[NOME TESTE],[MARCA TESTE],[MATRICULA])
VALUES ('0001','TESTE CARRO','TESTE MARCA','00166')

-------------------------------- DESAFIO MASTER   PARA CRIAR AS  RELAÇÕES DAS TABELAS DA AULA 6 ----------------------------------------

CREATE DATABASE [ESQUINA_VENDAS]

CREATE TABLE [TABELA DE CLIENTES](
	[CPF] [VARCHAR](11) ,
	[NOME] [VARCHAR](100) ,
	[ENDERECO] [VARCHAR](150) ,
	[COMPLEMENTO] [VARCHAR](150) ,
	[BAIRRO] [VARCHAR](50) ,
	[CIDADE] [VARCHAR](50) ,
	[ESTADO] [VARCHAR](2) ,
	[CEP] [VARCHAR](8) ,
	[DATA DE NASCIMENTO] [DATE] ,
	[IDADE] [SMALLINT ] ,
	[SEXO] [VARCHAR](1) ,
	[LIMITE DE CREDITO] [MONEY] ,
	[VOLUME DE COMPRA] [FLOAT] ,
	[PRIMEIRA COMPRA] [BIT] ,
 	PRIMARY KEY ([CPF])
)

CREATE TABLE [TABELA DE PRODUTOS](
	[CODIGO DO PRODUTO] [VARCHAR](10),
	[NOME DO PRODUTO] [VARCHAR](50),
	[EMBALAGEM] [VARCHAR](20),
	[TAMANHO] [VARCHAR](10),
	[SABOR] [VARCHAR](20),
	[PRECO DE LISTA] [SMALLMONEY],
	PRIMARY KEY ([CODIGO DO PRODUTO])
)

CREATE TABLE [TABELA DE VENDEDORES]
( [MATRICULA] [VARCHAR](5),
[NOME] [VARCHAR](100),
[PERCENTUAL COMISSAO] [FLOAT],
[DATA DE ADMISSAO][DATE],
[FERIAS][BIT]
PRIMARY KEY ([MATRICULA])

)


CREATE TABLE [TABELA DE NOTAS FISCAIS]
(
    [CPF] [VARCHAR] (11) NOT NULL,
    [MATRICULA] [VARCHAR](5) NOT NULL,
    [DATA] [DATE],
    [NUMERO][VARCHAR](6),
    [IMPOSTO][FLOAT],
    PRIMARY KEY ([NUMERO]),
    
	FOREIGN KEY ([CPF]) REFERENCES [TABELA DE CLIENTES] ([CPF]),

    FOREIGN KEY ([MATRICULA]) REFERENCES [TABELA DE VENDEDORES] ([MATRICULA])

)

CREATE TABLE [TABELA DE ITENS NOTAS FISCAIS]
(
    [NUMERO] [VARCHAR](6) NOT NULL,
    [CODIGO DO PRODUTO] [VARCHAR] (10) NOT NULL,
    [QUANTIDADE][INT],
    [PRECO][FLOAT],

	PRIMARY KEY([NUMERO],[CODIGO DO PRODUTO]),
    
    FOREIGN KEY ([NUMERO]) REFERENCES [TABELA DE NOTAS FISCAIS] ([NUMERO]),
    FOREIGN KEY ([CODIGO DO PRODUTO]) REFERENCES [TABELA DE PRODUTOS] ([CODIGO DO PRODUTO])

)

----------------------------- AULA 7 - FILTRANDO AS CONSULTAS DE DADOS ---------------------------------


SELECT * FROM [TABELA DE PRODUTOS] 
WHERE [SABOR] = 'Manga' OR [TAMANHO] = '700 ml' 



SELECT * FROM [TABELA DE PRODUTOS] 
WHERE [SABOR] = 'Manga' AND [TAMANHO] = '700 ml' 




SELECT * FROM [TABELA DE PRODUTOS] 
WHERE NOT ([SABOR] = 'Manga' AND [TAMANHO] = '700 ml')




SELECT * FROM [TABELA DE PRODUTOS] 
WHERE NOT ([SABOR] = 'Manga' OR [TAMANHO] = '700 ml')




SELECT * FROM [TABELA DE PRODUTOS] 
WHERE [SABOR] = 'Manga' AND NOT ( [TAMANHO] = '700 ml')




SELECT * FROM [TABELA DE PRODUTOS] 
WHERE [SABOR] IN ('Manga', 'Laranja')



SELECT * FROM [TABELA DE PRODUTOS] 
WHERE [SABOR] = 'Manga' OR [SABOR] ='Laranja'




SELECT * FROM [TABELA DE PRODUTOS] 
WHERE [SABOR] NOT IN ('Manga', 'Laranja')



SELECT * FROM [TABELA DE PRODUTOS]
WHERE NOT ([SABOR] = 'Manga' OR [SABOR] ='Laranja')



SELECT * FROM [TABELA DE PRODUTOS] 
WHERE [SABOR] IN ('Manga', 'Laranja') AND [PRECO DE LISTA] > 10



SELECT * FROM [TABELA DE PRODUTOS] 
WHERE [SABOR] IN ('Manga', 'Laranja') AND [PRECO DE LISTA] BETWEEN 10 AND 13




SELECT * FROM [TABELA DE PRODUTOS] 
WHERE [SABOR] IN ('Manga', 'Laranja') AND [PRECO DE LISTA] >= 10 AND [PRECO DE LISTA] <= 13



------------------------------ DESAFIO DE VOCES DA AULA 7---------------------------------

SELECT *  FROM [TABELA DE ITENS NOTAS FISCAIS]
WHERE [QUANTIDADE] > 60 AND [PREÇO] <= 3

------------------------- USANDO O LIKE --------------------------------------------------

SELECT * FROM [TABELA DE PRODUTOS]

SELECT * FROM [TABELA DE PRODUTOS] 
WHERE [NOME DO PRODUTO] LIKE '%Litros%'

SELECT * FROM [TABELA DE PRODUTOS] 
WHERE [NOME DO PRODUTO] LIKE 'Litros%'

SELECT * FROM [TABELA DE PRODUTOS] 
WHERE [NOME DO PRODUTO] LIKE '%Litros%' AND [SABOR] = 'Laranja'



--------------------------------- FIM da aula 07 ----------------------------------------------------



------------------------ Aula 8  – Mudando a apresentação dos dados de uma consulta ---------------------------------- 


--Usando distinct para visualizar tabela

SELECT EMBALAGEM, TAMANHO FROM [TABELA DE PRODUTOS]

SELECT DISTINCT EMBALAGEM, TAMANHO FROM [TABELA DE PRODUTOS]

SELECT DISTINCT EMBALAGEM, TAMANHO FROM [TABELA DE PRODUTOS] 
WHERE[SABOR] = 'Laranja'

SELECT DISTINCT EMBALAGEM, TAMANHO, SABOR FROM [TABELA DE PRODUTOS]


-- ------------------------------------- Desafio 01 da aula 08 ---------------------------------------------------


SELECT DISTINCT BAIRRO FROM [TABELA DE CLIENTES]
WHERE CIDADE = 'Rio de Janeiro'

-------------------------------- Limitando a saída de consulta ---------------------------------------

SELECT * FROM [TABELA DE PRODUTOS]

SELECT TOP 3 * FROM [TABELA DE PRODUTOS]

SELECT * FROM [TABELA DE PRODUTOS] 
WHERE [SABOR] = 'Laranja'

SELECT TOP 3 * FROM [TABELA DE PRODUTOS] 
WHERE [SABOR] = 'Laranja'

SELECT EMBALAGEM, TAMANHO FROM [TABELA DE PRODUTOS]

SELECT DISTINCT EMBALAGEM, TAMANHO FROM [TABELA DE PRODUTOS]

SELECT DISTINCT TOP 3 EMBALAGEM, TAMANHO FROM [TABELA DE PRODUTOS]

----------------------------- Desafio 02 da Aula 08-------------------------------------------------- 

SELECT TOP 10 * FROM [TABELA DE NOTAS FISCAIS] 
WHERE [DATA] = '2017-01-01'


----------------------------- Ordenando a saída da consulta ----------------------------------------

SELECT * FROM [TABELA DE PRODUTOS]

SELECT * FROM [TABELA DE PRODUTOS] 
ORDER BY [PRECO DE LISTA]

SELECT * FROM [TABELA DE PRODUTOS] 
ORDER BY [PRECO DE LISTA] DESC

SELECT * FROM [TABELA DE PRODUTOS] 
ORDER BY [NOME DO PRODUTO]

SELECT [EMBALAGEM], [NOME DO PRODUTO] FROM [TABELA DE PRODUTOS] 
ORDER BY [EMBALAGEM], [NOME DO PRODUTO]

SELECT [EMBALAGEM], [NOME DO PRODUTO] FROM [TABELA DE PRODUTOS] 
ORDER BY [EMBALAGEM], [NOME DO PRODUTO] DESC


SELECT [EMBALAGEM], [NOME DO PRODUTO] FROM [TABELA DE PRODUTOS] 
ORDER BY [EMBALAGEM] DESC, [NOME DO PRODUTO] DESC


SELECT [EMBALAGEM], [NOME DO PRODUTO] FROM [TABELA DE PRODUTOS] 
ORDER BY [EMBALAGEM] DESC, [NOME DO PRODUTO] ASC


------------------------------- Desafio 03 da Aula 08 ------------------------------------------

SELECT * FROM [TABELA DE PRODUTOS] 
WHERE [NOME DO PRODUTO] = 'Linha Refrescante - 1 Litro - Morango/Limão'

SELECT * FROM [TABELA DE PRODUTOS] 
WHERE [NOME DO PRODUTO] LIKE '%Morango/Limão%'

SELECT * FROM [TABELA DE PRODUTOS] 
WHERE [NOME DO PRODUTO] LIKE '%Refrescante%'



SELECT * FROM [TABELA DE ITENS NOTAS FISCAIS]
WHERE [CODIGO DO PRODUTO] = '1101035'
ORDER BY QUANTIDADE DESC


---------------------------------- Agrupando os resultados ----------------------

SELECT * FROM [TABELA DE CLIENTES]

SELECT ESTADO,  [LIMITE DE CREDITO] FROM [TABELA DE CLIENTES]

SELECT ESTADO, SUM([LIMITE DE CREDITO]) FROM [TABELA DE CLIENTES] 
GROUP BY ESTADO

SELECT ESTADO, SUM([LIMITE DE CREDITO]) AS 'LIMITE DE CREDITO' FROM [TABELA DE CLIENTES] 
GROUP BY ESTADO


SELECT ESTADO, AVG([LIMITE DE CREDITO]) FROM [TABELA DE CLIENTES] 
GROUP BY ESTADO



SELECT ESTADO, AVG([LIMITE DE CREDITO]) AS 'MEDIA DO LIMITE DE CREDITO' FROM [TABELA DE CLIENTES] 
GROUP BY ESTADO





SELECT * FROM [TABELA DE PRODUTOS]


SELECT EMBALAGEM, MAX([PRECO DE LISTA]) FROM [TABELA DE PRODUTOS] 
GROUP BY EMBALAGEM

SELECT EMBALAGEM, MAX([PRECO DE LISTA]) AS 'VALOR MAIS CARO POR EMBALAGEM' FROM [TABELA DE PRODUTOS] 
GROUP BY EMBALAGEM



SELECT EMBALAGEM, MIN([PRECO DE LISTA]) FROM [TABELA DE PRODUTOS] 
GROUP BY EMBALAGEM

SELECT EMBALAGEM, COUNT(*) FROM [TABELA DE PRODUTOS] 
GROUP BY EMBALAGEM



SELECT [NOME DO PRODUTO], EMBALAGEM  FROM [TABELA DE PRODUTOS] 
ORDER BY EMBALAGEM






SELECT BAIRRO, SUM([LIMITE DE CREDITO]) FROM [TABELA DE CLIENTES] 
WHERE [ESTADO]  = 'SP' 
GROUP BY BAIRRO


SELECT BAIRRO, SUM([LIMITE DE CREDITO]) FROM [TABELA DE CLIENTES] 
WHERE [ESTADO]  = 'SP' 
GROUP BY BAIRRO ORDER BY BAIRRO DESC


SELECT BAIRRO, ESTADO, SUM([LIMITE DE CREDITO]) FROM [TABELA DE CLIENTES] 
WHERE [ESTADO]  = 'SP' 
GROUP BY BAIRRO, ESTADO


------------- DESAFIO 4 AULA 08 ----


SELECT * FROM [TABELA DE PRODUTOS] 
WHERE [NOME DO PRODUTO] LIKE '%Morango/Limão%'



SELECT * FROM [TABELA DE PRODUTOS] 
WHERE [NOME DO PRODUTO] = 'Linha Refrescante - 1 Litro - Morango/Limão'





SELECT * FROM [TABELA DE ITENS NOTAS FISCAIS]
WHERE [CODIGO DO PRODUTO] = '1101035'
ORDER BY QUANTIDADE DESC


SELECT [CODIGO DO PRODUTO], COUNT(*) AS 'QUANTIDADE VENDIDADE' FROM [TABELA DE ITENS NOTAS FISCAIS]
WHERE [CODIGO DO PRODUTO] = '1101035'
AND QUANTIDADE = 99
GROUP BY [CODIGO DO PRODUTO]


--------------------------------- FIM da aula 08 ----------------------------------------------------


------------ Aula 9 - Juntando tabelas e consultas -----------



-----------------------  Consultas com Having ------------------------------------------------------------------

SELECT BAIRRO, ESTADO, SUM([LIMITE DE CREDITO]) FROM [TABELA DE CLIENTES] 
WHERE [ESTADO]  = 'SP' 
GROUP BY BAIRRO, ESTADO




SELECT BAIRRO, ESTADO, SUM([LIMITE DE CREDITO]) AS 'SOMA DE LIMITES DE CREDITO' FROM [TABELA DE CLIENTES] 
WHERE [ESTADO]  = 'SP' 
GROUP BY BAIRRO, ESTADO
HAVING SUM([LIMITE DE CREDITO])>= 140000




SELECT * FROM [dbo].[TABELA DE CLIENTES]


SELECT ESTADO, SUM([LIMITE DE CREDITO]) 'SOMA LIMITE DE CREDITO' FROM [TABELA DE CLIENTES] 
GROUP BY ESTADO



SELECT ESTADO, SUM([LIMITE DE CREDITO]) FROM [TABELA DE CLIENTES] 
GROUP BY ESTADO 
HAVING SUM([LIMITE DE CREDITO]) >= 850000



SELECT EMBALAGEM, SUM([PRECO DE LISTA]), MAX([PRECO DE LISTA]), MIN([PRECO DE LISTA]) 
FROM [TABELA DE PRODUTOS] 
GROUP BY EMBALAGEM

SELECT EMBALAGEM, SUM([PRECO DE LISTA]) AS 'SOMA PREÇO', MAX([PRECO DE LISTA]) AS 'MAIOR PREÇO', MIN([PRECO DE LISTA]) AS 'MENOR PRECO' 
FROM [TABELA DE PRODUTOS] 
GROUP BY EMBALAGEM



SELECT EMBALAGEM, SUM([PRECO DE LISTA]) AS 'SOMA PREÇO', MAX([PRECO DE LISTA]) AS 'MAIOR PREÇO', MIN([PRECO DE LISTA]) AS 'MENOR PRECO' 
FROM [TABELA DE PRODUTOS] 
GROUP BY EMBALAGEM
HAVING  SUM([PRECO DE LISTA])<=80


SELECT EMBALAGEM, SUM([PRECO DE LISTA]) AS 'SOMA PREÇO', MAX([PRECO DE LISTA]) AS 'MAIOR PREÇO', MIN([PRECO DE LISTA]) AS 'MENOR PRECO' 
FROM [TABELA DE PRODUTOS] 
GROUP BY EMBALAGEM
HAVING SUM([PRECO DE LISTA]) <= 80 AND MAX([PRECO DE LISTA]) >= 6


---------------------- DESAFIO 1 AULA 09 ----------------------------------------------------

SELECT CPF, COUNT(*) AS 'QTD. DE COMPRAS' FROM  [TABELA DE NOTAS FISCAIS]
WHERE YEAR(DATA) = 2016 
GROUP BY CPF 
HAVING COUNT(*) > 2000

-- 3 CLIENTES

--------------------------------------- USANDO O CASE PARA CLASSIFICAR RESULTADOS ----------------------------------------



SELECT * FROM [TABELA DE PRODUTOS]

----------------------------------------------------------

SELECT [NOME DO PRODUTO],
	CASE 
		WHEN [PRECO DE LISTA] >= 12 THEN 'PRODUTO CARO'
		WHEN [PRECO DE LISTA] >= 7 AND [PRECO DE LISTA] < 12 THEN 'PRODUTO EM CONTA'
		ELSE 'PRODUTO BARATO' 
	END
FROM [TABELA DE PRODUTOS]

-------------------------------------------------------

SELECT [NOME DO PRODUTO],
	CASE 
		WHEN [PRECO DE LISTA] >= 12 THEN 'PRODUTO CARO'
		WHEN [PRECO DE LISTA] >= 7 AND [PRECO DE LISTA] < 12 THEN 'PRODUTO EM CONTA'
		ELSE 'PRODUTO BARATO' 
	END AS 'CLASSIFICÃO DO PRODUTO'
FROM [TABELA DE PRODUTOS]

---------------------------------------------------------

SELECT [NOME DO PRODUTO],[PRECO DE LISTA],
	CASE 
		WHEN [PRECO DE LISTA] >= 12 THEN 'PRODUTO CARO'
		WHEN [PRECO DE LISTA] >= 7 AND [PRECO DE LISTA] < 12 THEN 'PRODUTO EM CONTA'
		ELSE 'PRODUTO BARATO' 
	END AS 'CLASSIFICÃO DO PRODUTO'
FROM [TABELA DE PRODUTOS]

----------------------------------------------

SELECT [NOME DO PRODUTO],[PRECO DE LISTA],
	CASE 
		WHEN [PRECO DE LISTA] >= 12 THEN 'PRODUTO CARO'
		WHEN [PRECO DE LISTA] >= 7 AND [PRECO DE LISTA] < 12 THEN 'PRODUTO EM CONTA'
		ELSE 'PRODUTO BARATO' 
	END AS 'CLASSIFICÃO DO PRODUTO'
FROM [TABELA DE PRODUTOS]
ORDER BY [PRECO DE LISTA]

-----------------------------------

SELECT [NOME DO PRODUTO],
		CASE 
		WHEN [PRECO DE LISTA] >= 12 THEN 'PRODUTO CARO'
		WHEN [PRECO DE LISTA] >= 7 AND [PRECO DE LISTA] < 12 THEN 'PRODUTO EM CONTA'
		ELSE 'PRODUTO BARATO' 
		END, AVG([PRECO DE LISTA])

FROM [TABELA DE PRODUTOS]

GROUP BY 
[NOME DO PRODUTO],
CASE 
	WHEN [PRECO DE LISTA] >= 12 THEN 'PRODUTO CARO'
	WHEN [PRECO DE LISTA] >= 7 AND [PRECO DE LISTA] < 12 THEN 'PRODUTO EM CONTA'
	ELSE 'PRODUTO BARATO' 
END

-------------------------------------------------------

SELECT [NOME DO PRODUTO],
		CASE 
		WHEN [PRECO DE LISTA] >= 12 THEN 'PRODUTO CARO'
		WHEN [PRECO DE LISTA] >= 7 AND [PRECO DE LISTA] < 12 THEN 'PRODUTO EM CONTA'
		ELSE 'PRODUTO BARATO' 
		END AS 'CLASSIFICAÇÃO DO PRODUTO', AVG([PRECO DE LISTA]) AS 'MÉDIA'

FROM [TABELA DE PRODUTOS]

GROUP BY 
[NOME DO PRODUTO],
CASE 
	WHEN [PRECO DE LISTA] >= 12 THEN 'PRODUTO CARO'
	WHEN [PRECO DE LISTA] >= 7 AND [PRECO DE LISTA] < 12 THEN 'PRODUTO EM CONTA'
	ELSE 'PRODUTO BARATO' 
END 

------------------------------------------------------------

SELECT * FROM [TABELA DE NOTAS FISCAIS]


SELECT COUNT (*) FROM [TABELA DE NOTAS FISCAIS]


SELECT [DATA], COUNT (*) AS 'CONTAGEM' FROM [TABELA DE NOTAS FISCAIS]
GROUP BY [DATA]


SELECT YEAR(DATA) AS 'ANO', COUNT(*) AS 'CONTAGEM' FROM [TABELA DE NOTAS FISCAIS]
GROUP BY YEAR(DATA)

--------------------------------------------------------------

-------------------- DESAFIO 2 DA AULA 09 ----------------------------------------------

SELECT [NOME],
	CASE 
		WHEN YEAR([DATA DE NASCIMENTO]) < 1990 THEN 'Adulto'
		WHEN year([DATA DE NASCIMENTO]) between 1990 and 1995 then 'Jovem'
		ELSE 'Criança' 
	END AS 'CLASSIFICAÇÃO ETÁRIA'
FROM [TABELA DE CLIENTES]
 ----------------------------------------------------------

 ------------------INNER JOIN-----------------------------------------------


SELECT * FROM [TABELA DE VENDEDORES]


SELECT * FROM [TABELA DE NOTAS FISCAIS]


SELECT * FROM [TABELA DE VENDEDORES] 
INNER JOIN  [TABELA DE NOTAS FISCAIS]
ON [TABELA DE VENDEDORES].MATRICULA = [TABELA DE NOTAS FISCAIS].MATRICULA


SELECT * FROM [TABELA DE VENDEDORES] A
INNER JOIN [TABELA DE NOTAS FISCAIS] B 
ON A.MATRICULA = B.MATRICULA

 




SELECT [TABELA DE VENDEDORES].MATRICULA, [TABELA DE VENDEDORES].[NOME], COUNT(*) AS 'NOTA FISCAL POR VENDEDOR' FROM [TABELA DE VENDEDORES] 
INNER JOIN [TABELA DE NOTAS FISCAIS] 
ON [TABELA DE VENDEDORES].MATRICULA = [TABELA DE NOTAS FISCAIS].MATRICULA
GROUP BY [TABELA DE VENDEDORES].MATRICULA, [TABELA DE VENDEDORES].[NOME]


SELECT [TABELA DE VENDEDORES].MATRICULA, [TABELA DE VENDEDORES].[NOME], COUNT(*) AS 'NOTA FISCAL POR VENDEDOR' FROM [TABELA DE VENDEDORES] 
INNER JOIN [TABELA DE NOTAS FISCAIS] 
ON [TABELA DE VENDEDORES].MATRICULA = [TABELA DE NOTAS FISCAIS].MATRICULA
GROUP BY [TABELA DE VENDEDORES].MATRICULA, [TABELA DE VENDEDORES].[NOME]
ORDER BY  COUNT(*)


SELECT [TABELA DE VENDEDORES].MATRICULA, [TABELA DE VENDEDORES].[NOME], YEAR(DATA) AS 'DATA', 
COUNT(*) AS 'NOTA FISCAL POR VENDEDOR' FROM [TABELA DE VENDEDORES] INNER JOIN 
[TABELA DE NOTAS FISCAIS] ON [TABELA DE VENDEDORES].MATRICULA = [TABELA DE NOTAS FISCAIS].MATRICULA
GROUP BY [TABELA DE VENDEDORES].MATRICULA, [TABELA DE VENDEDORES].[NOME], YEAR(DATA)


SELECT [TABELA DE VENDEDORES].MATRICULA, [TABELA DE VENDEDORES].[NOME], YEAR(DATA) AS 'DATA', 
COUNT(*) AS 'NOTA FISCAL POR VENDEDOR' FROM [TABELA DE VENDEDORES] INNER JOIN 
[TABELA DE NOTAS FISCAIS] ON [TABELA DE VENDEDORES].MATRICULA = [TABELA DE NOTAS FISCAIS].MATRICULA
GROUP BY [TABELA DE VENDEDORES].MATRICULA, [TABELA DE VENDEDORES].[NOME], YEAR(DATA)
ORDER BY YEAR(DATA)

-------------------- ------DESAFIO 03 DA AULA 09 ---------------------------------------


SELECT YEAR(DATA) AS 'ANO', SUM (QUANTIDADE * [PREÇO]) AS 'FATURAMENTO'
FROM [TABELA DE NOTAS FISCAIS] NF 
INNER JOIN [TABELA DE ITENS NOTAS FISCAIS] INF 
ON NF.NUMERO = INF.NUMERO
GROUP BY YEAR(DATA)

---------------------------- LEFT JOIN ----------------------------------------------



SELECT * FROM [TABELA DE CLIENTES] INNER JOIN 
[TABELA DE NOTAS FISCAIS] ON [TABELA DE CLIENTES].CPF = [TABELA DE NOTAS FISCAIS].CPF




SELECT [TABELA DE CLIENTES].[NOME], COUNT(*) AS 'QTD. DE NOTAS POR CLIENTE' FROM [TABELA DE CLIENTES] INNER JOIN 
[TABELA DE NOTAS FISCAIS]ON [TABELA DE CLIENTES].CPF = [TABELA DE NOTAS FISCAIS].CPF
GROUP BY [TABELA DE CLIENTES].[NOME]


SELECT * FROM [TABELA DE CLIENTES]




SELECT [TABELA DE CLIENTES].[NOME], COUNT(*) AS 'QTD. DE NOTAS POR CLIENTE' FROM [TABELA DE CLIENTES]
LEFT JOIN [TABELA DE NOTAS FISCAIS] 
ON [TABELA DE CLIENTES].CPF = [TABELA DE NOTAS FISCAIS].CPF
GROUP BY [TABELA DE CLIENTES].[NOME]



SELECT [TABELA DE CLIENTES].[CPF], [TABELA DE CLIENTES].[NOME], COUNT(*) FROM [TABELA DE CLIENTES]
LEFT JOIN [TABELA DE NOTAS FISCAIS]
ON [TABELA DE CLIENTES].CPF = [TABELA DE NOTAS FISCAIS].CPF
GROUP BY  [TABELA DE CLIENTES].[CPF], [TABELA DE CLIENTES].[NOME]


SELECT * FROM [TABELA DE NOTAS FISCAIS]
WHERE CPF = '95939180787'

-------------------------- UNION --------------------------------------------------------

SELECT DISTINCT BAIRRO AS 'BAIRRO CLIENTE' FROM [TABELA DE CLIENTES]

SELECT DISTINCT BAIRRO AS 'BAIRRO VENDEDORES' FROM [TABELA DE VENDEDORES]



SELECT  BAIRRO AS 'BAIRRO' FROM [TABELA DE CLIENTES]
UNION 
SELECT  BAIRRO AS 'BAIRRO' FROM [TABELA DE VENDEDORES]


SELECT  BAIRRO AS 'BAIRRO' FROM [TABELA DE CLIENTES]
UNION ALL
SELECT  BAIRRO AS 'BAIRRO' FROM [TABELA DE VENDEDORES]


SELECT  BAIRRO, [DATA DE NASCIMENTO] FROM [TABELA DE CLIENTES]
UNION ALL
SELECT  BAIRRO, NOME FROM [TABELA DE VENDEDORES]


SELECT  BAIRRO, NOME FROM [TABELA DE CLIENTES]
UNION ALL
SELECT  BAIRRO, NOME FROM [TABELA DE VENDEDORES]

--- um pouco de constantes ------
SELECT 'TESTE' AS 'COLUNA'

SELECT 1 AS 'TESTE'

SELECT 'TESTE' AS 'COLUNA', BAIRRO, NOME  FROM [TABELA DE CLIENTES]


SELECT BAIRRO, NOME, 'CLIENTE' AS 'CLIENTE/VENDEDOR' FROM [TABELA DE CLIENTES]
UNION ALL
SELECT  BAIRRO, NOME, 'VENDEDOR' FROM [TABELA DE VENDEDORES]
ORDER BY 3 DESC


------------- ----------SUBCONSULTAS ---------------------------------


SELECT NOME, BAIRRO FROM [TABELA DE CLIENTES]



SELECT BAIRRO FROM [TABELA DE VENDEDORES]



SELECT NOME, BAIRRO FROM [TABELA DE CLIENTES]
WHERE BAIRRO IN (SELECT BAIRRO FROM [TABELA DE VENDEDORES])



SELECT EMBALAGEM, MAX([PRECO DE LISTA]) AS 'PRECO MAXIMO POR EMBALAGEM' FROM [TABELA DE PRODUTOS]
GROUP BY EMBALAGEM



SELECT EMBALAGEM, MAX([PRECO DE LISTA]) AS 'PRECO MAXIMO POR EMBALAGEM' FROM [TABELA DE PRODUTOS]
GROUP BY EMBALAGEM
HAVING MAX([PRECO DE LISTA])<5


SELECT A.EMBALAGEM,A.[PRECO MAXIMO POR EMBALAGEM] FROM (SELECT EMBALAGEM, MAX([PRECO DE LISTA]) AS 'PRECO MAXIMO POR EMBALAGEM' FROM [TABELA DE PRODUTOS]
GROUP BY EMBALAGEM) A 
WHERE A.[PRECO MAXIMO POR EMBALAGEM]<=5


--------------------------Visão------------------------------------------

-- criamos essa view pelo assitente 
SELECT * FROM [VW_EMBALAGEM]




--CRIACAO POR SQL
CREATE VIEW VW_TESTE AS 
		
	SELECT EMBALAGEM, MAX([PRECO DE LISTA]) AS 'PRECO MAXIMO POR EMBALAGEM' 
	FROM [TABELA DE PRODUTOS]
	GROUP BY EMBALAGEM

--SELECT NA VIEW TESTE
SELECT * FROM VW_TESTE








--------------------------------------------- Aula 10 - Funções do SQL Server ----------------------------------




---------- Funções de String ------------------



-- LTRIM
SELECT LTRIM('      OLA') as 'CAMPO'

SELECT ('           OLA') as 'CAMPO'


--RTRIM
SELECT RTRIM ('OLA           ') AS 'CAMPO'



SELECT REPLACE (TRIM ('                         MARCIO LADISLAU'         ),' ','')


--CONCAT
SELECT CONCAT('OLA ','MUNDO') AS 'CAMPO'

SELECT 'OLA ' + 'MUNDO'


--LEFT
SELECT LEFT ('AVENIDA EDUARDO RIBEIRO',7) AS 'CAMPO'

--RIGHT
SELECT RIGHT ('AVENIDA EDUARDO RIBEIRO',7) AS 'CAMPO'

--LOWER
SELECT LOWER('AVENIDA EDUARDO RIBEIRO') AS 'CAMPO'

--UPPER
SELECT UPPER ('avenida eduardo ribeiro') AS 'CAMPO'

--REPLACE
SELECT REPLACE ('AVENIDA EDUARDO RIBEIRO','AVENIDA','RUA') AS 'CAMPO'

--SUBSTRING
SELECT SUBSTRING ('AVENIDA EDUARDO RIBEIRO',1,7) AS CAMPO

SELECT SUBSTRING ('AVENIDA EDUARDO RIBEIRO',9,7) AS CAMPO


--LEN
SELECT LEN ('AVENIDA EDUARDO RIBEIRO') AS 'CAMPO'



--TESTANDO NA TABELA
SELECT * FROM [TABELA DE CLIENTES]

SELECT CONCAT(NOME, ' (',CPF,')') AS 'CAMPO TESTE' FROM [TABELA DE CLIENTES]


-------------------- DESAFIO 01 DA AULA 10 ---------------

SELECT NOME, CONCAT([ENDERECO], ' ', BAIRRO, ' ', CIDADE, ' ', ESTADO) AS 'ENDERECO COMPLETO'
FROM [TABELA DE CLIENTES]


---------------FUNÇOES DE DATA ------------------------------------------------


SELECT SYSDATETIME()

SELECT SYSDATETIMEOFFSET()

SELECT SYSUTCDATETIME()

SELECT CURRENT_TIMESTAMP

SELECT GETDATE()

SELECT GETUTCDATE()


--ALGUMAS FUNÇÕES
SELECT DATENAME(YEAR,GETDATE())

SELECT DATENAME(MICROSECOND,GETDATE())

SELECT DATENAME(MINUTE,GETDATE())


SELECT DATENAME(MONTH,GETDATE())

SELECT DATENAME(WEEKDAY,GETDATE())

SELECT DATEPART(MONTH,GETDATE())

SELECT DAY(GETDATE())

SELECT YEAR(GETDATE())

SELECT DATEFROMPARTS(2020,5,24)

SELECT DATENAME(MONTH,DATEFROMPARTS(2020,5,1))

SELECT DATEDIFF(YEAR, DATEFROMPARTS(2019,9,1), GETDATE())

SELECT DATEADD(MONTH, 7, GETDATE())

SELECT ISDATE('2018-01-01')

SELECT ISDATE('2018-25-28')

SELECT * FROM [TABELA DE NOTAS FISCAIS] 

SELECT DATA, CONCAT(DATENAME(DAY,DATA),' de ',DATENAME(MONTH,DATA),' de ', DATENAME(YEAR,DATA)) AS 'DATA 2' FROM [TABELA DE NOTAS FISCAIS] 

----------------- DESAFIO 02 DA AULA  --------------------


--Crie uma consulta que mostre o nome e a idade dos clientes
SELECT NOME, DATEDIFF(YEAR, [DATA DE NASCIMENTO], GETDATE()) AS 'IDADE'
FROM [TABELA DE CLIENTES]


--------------------- FUNCOES NUMERICAS -----------------------------------------

SELECT CEILING(7.333223)

SELECT FLOOR(7.333223)

select 2 * rand()

SELECT 3* RAND()

SELECT ROUND(7.33323323, 2)

SELECT * FROM [TABELA DE ITENS NOTAS FISCAIS]

SELECT [QUANTIDADE], [PRECO], ROUND(([QUANTIDADE] * [PRECO]),1) FROM [TABELA DE ITENS NOTAS FISCAIS]


-- DESAFIO 03  DA AULA 10 ---------------------

SELECT YEAR(DATA) AS 'ANO', FLOOR(SUM(IMPOSTO * (QUANTIDADE * PRECO))) AS 'IMPOSTO PAGO' 
FROM [TABELA DE NOTAS FISCAIS] NF
INNER JOIN  [TABELA DE ITENS NOTAS FISCAIS]INF 
ON NF.NUMERO = INF.NUMERO
WHERE YEAR(DATA) = 2016
GROUP BY YEAR(DATA)




--------------------- CONVERSÃO DE DADOS --------------------------------------------

SELECT CONVERT(VARCHAR, GETDATE(), 101)

SELECT CONVERT(VARCHAR, GETDATE(), 113)

SELECT CONVERT(VARCHAR, GETDATE(), 130)

SELECT CONVERT(decimal(10,5), 193.57)

SELECT * FROM [TABELA DE PRODUTOS]


-- ERRO EXEMPLO
SELECT 'O preço do produto ' + [NOME DO PRODUTO] + ' é ' +  [PRECO DE LISTA] 
from [TABELA DE PRODUTOS]

SELECT 'O preço do produto ' + [NOME DO PRODUTO] + ' é ' +  CONVERT(VARCHAR, [PRECO DE LISTA])from [TABELA DE PRODUTOS]

SELECT CONCAT ('PRECO DE LISTA: ',[PRECO DE LISTA]) FROM [TABELA DE PRODUTOS]



-----------------------------------AULA 11 - RELATÓRIOS --------------------------

--PASSO 1: RELATORIO DE VENDAS VALIDAS

SELECT * FROM [TABELA DE CLIENTES]

SELECT * FROM [TABELA DE ITENS NOTAS FISCAIS]

SELECT * FROM [TABELA DE NOTAS FISCAIS]

--PASSO 2:  FACO A UNIAO DAS TABELAS QUE TEM OS VALORES QUE EU QUERO
SELECT * FROM [TABELA DE NOTAS FISCAIS] NF
INNER JOIN [TABELA DE ITENS NOTAS FISCAIS]INF
ON NF.NUMERO = INF.NUMERO


--PASSO 3:  PEGO SOMENTE OS CAMPOS QUE EU QUERO
SELECT NF.CPF, NF.DATA,INF.QUANTIDADE FROM [TABELA DE NOTAS FISCAIS] NF
INNER JOIN [TABELA DE ITENS NOTAS FISCAIS]INF
ON NF.NUMERO = INF.NUMERO


--PASSO 4: CONVERTENDO A DATA PARA STRING
SELECT NF.CPF, CONVERT (VARCHAR,NF.DATA,120) AS 'DATA',INF.QUANTIDADE FROM [TABELA DE NOTAS FISCAIS] NF
INNER JOIN [TABELA DE ITENS NOTAS FISCAIS]INF
ON NF.NUMERO = INF.NUMERO


--PASSO 5: USANDO SUBSTRING PARA PEGAR SOMENTE O ANO/MES
SELECT NF.CPF,SUBSTRING (CONVERT(VARCHAR,NF.DATA,120),1,7) AS 'ANO/MES',INF.QUANTIDADE FROM [TABELA DE NOTAS FISCAIS] NF
INNER JOIN [TABELA DE ITENS NOTAS FISCAIS]INF
ON NF.NUMERO = INF.NUMERO




--PASSO 6: AGRUPANDO PARA TER QUANTIDADE POR CPF E MÊS 
SELECT NF.CPF,SUBSTRING (CONVERT(VARCHAR,NF.DATA,120),1,7) AS 'ANO/MES', SUM (INF.QUANTIDADE) AS 'QUANTIDADE MES' FROM [TABELA DE NOTAS FISCAIS] NF
INNER JOIN [TABELA DE ITENS NOTAS FISCAIS]INF
ON NF.NUMERO = INF.NUMERO
GROUP BY NF.CPF, SUBSTRING (CONVERT(VARCHAR,NF.DATA,120),1,7)



--PASSO 7: PEGAR O NOME E VOLUME DE COMPRA DA TABELA DE CLIENTE
SELECT TC.NOME,TC.[VOLUME DE COMPRA] FROM [TABELA DE CLIENTES]TC






--PASSO 8: FAZENDO SUBQUERY DA CONSULTA 
SELECT * FROM
(SELECT NF.CPF,SUBSTRING(CONVERT (VARCHAR,NF.[DATA],103),4,10) AS 'MES/ANO', SUM (INF.QUANTIDADE) AS 'QUANTIDADE MES' FROM [TABELA DE NOTAS FISCAIS]NF
INNER JOIN [TABELA DE ITENS NOTAS FISCAIS]INF
ON NF.NUMERO = INF.NUMERO
GROUP BY  NF.CPF,SUBSTRING(CONVERT (VARCHAR,NF.[DATA],103),4,10))CQ


--PASSO 9: APLICANDO INNER JOIN COM A TABELA DE CLIENTES
SELECT * FROM
(SELECT NF.CPF,SUBSTRING(CONVERT (VARCHAR,NF.[DATA],103),4,10) AS 'MES/ANO', SUM (INF.QUANTIDADE) AS 'QUANTIDADE MES' FROM [TABELA DE NOTAS FISCAIS]NF
INNER JOIN [TABELA DE ITENS NOTAS FISCAIS]INF
ON NF.NUMERO = INF.NUMERO
GROUP BY  NF.CPF,SUBSTRING(CONVERT (VARCHAR,NF.[DATA],103),4,10))CQ
INNER JOIN [TABELA DE CLIENTES]TC
ON TC.CPF = CQ.CPF


--PASSO 10: SELECIONADO SOMENTE AS COLUNAS NECESSARIAS
SELECT TC.NOME,CQ.[ANO/MES], CQ.[QUANTIDADE MES],TC.[VOLUME DE COMPRA]
FROM
(SELECT NF.CPF,SUBSTRING (CONVERT(VARCHAR,NF.DATA,120),1,7) AS 'ANO/MES', SUM (INF.QUANTIDADE) AS 'QUANTIDADE MES' FROM [TABELA DE NOTAS FISCAIS] NF
INNER JOIN [TABELA DE ITENS NOTAS FISCAIS]INF
ON NF.NUMERO = INF.NUMERO
GROUP BY NF.CPF, SUBSTRING (CONVERT(VARCHAR,NF.DATA,120),1,7))CQ --
INNER JOIN [TABELA DE CLIENTES]TC
ON TC.CPF = CQ.CPF



--PASSO 11: ELA VAI SER OUTRA SUBQUERY
--OBSERVEM O APELIDO PESSOAL

SELECT * FROM
(SELECT TC.NOME,CQ.[ANO/MES], CQ.[QUANTIDADE MES],TC.[VOLUME DE COMPRA]
FROM
(SELECT NF.CPF,SUBSTRING (CONVERT(VARCHAR,NF.DATA,120),1,7) AS 'ANO/MES', SUM (INF.QUANTIDADE) AS 'QUANTIDADE MES' FROM [TABELA DE NOTAS FISCAIS] NF
INNER JOIN [TABELA DE ITENS NOTAS FISCAIS]INF
ON NF.NUMERO = INF.NUMERO
GROUP BY NF.CPF, SUBSTRING (CONVERT(VARCHAR,NF.DATA,120),1,7))CQ --
INNER JOIN [TABELA DE CLIENTES]TC
ON TC.CPF = CQ.CPF)AUX


--PASSO 12: PEGANDO SOMENTE O QUE EU QUERO JÁ COM O CASE EMBUTIDO NO SELECT

SELECT AUX.NOME,AUX.[MES/ANO],AUX.[QUANTIDADE MES],AUX.[VOLUME DE COMPRA],
CASE
	WHEN AUX.[QUANTIDADE MES] <= AUX.[VOLUME DE COMPRA] THEN 'VENDA VÁLIDA'
	ELSE 'VENDA INVALIDA' 

END AS 'STATUS DE VENDA'
FROM
(SELECT TC.NOME,CQ.[MES/ANO], CQ.[QUANTIDADE MES],TC.[VOLUME DE COMPRA]
FROM
(SELECT NF.CPF,SUBSTRING(CONVERT (VARCHAR,NF.[DATA],103),4,10) AS 'MES/ANO', SUM (INF.QUANTIDADE) AS 'QUANTIDADE MES' FROM [TABELA DE NOTAS FISCAIS]NF
INNER JOIN [TABELA DE ITENS NOTAS FISCAIS]INF
ON NF.NUMERO = INF.NUMERO
GROUP BY  NF.CPF,SUBSTRING(CONVERT (VARCHAR,NF.[DATA],103),4,10))CQ
INNER JOIN [TABELA DE CLIENTES]TC
ON TC.CPF = CQ.CPF)AUX



--PASSO 13: ORDANANDO PELO ORDER BY PELO NOME E MES/ANO
SELECT AUX.NOME,AUX.[MES/ANO],AUX.[QUANTIDADE MES],AUX.[VOLUME DE COMPRA],
CASE
	WHEN AUX.[QUANTIDADE MES] <= AUX.[VOLUME DE COMPRA] THEN 'VENDA VÁLIDA'
	ELSE 'VENDA INVALIDA' 

END AS 'STATUS DE VENDA'
FROM
(SELECT TC.NOME,CQ.[MES/ANO], CQ.[QUANTIDADE MES],TC.[VOLUME DE COMPRA]
FROM
(SELECT NF.CPF,SUBSTRING(CONVERT (VARCHAR,NF.[DATA],103),4,10) AS 'MES/ANO', SUM (INF.QUANTIDADE) AS 'QUANTIDADE MES' FROM [TABELA DE NOTAS FISCAIS]NF
INNER JOIN [TABELA DE ITENS NOTAS FISCAIS]INF
ON NF.NUMERO = INF.NUMERO
GROUP BY  NF.CPF,SUBSTRING(CONVERT (VARCHAR,NF.[DATA],103),4,10))CQ
INNER JOIN [TABELA DE CLIENTES]TC
ON TC.CPF = CQ.CPF)AUX
ORDER BY AUX.NOME, AUX.[MES/ANO]





-- RESPOSTA DO DESAFIO DO RELATORIO DE VENDA ---------

SELECT AUX.NOME, AUX.[ANO/MES],AUX.[QUANTIDADE MES],AUX.[VOLUME DE COMPRA], 
 ROUND ((1 -(AUX.[VOLUME DE COMPRA]/AUX.[QUANTIDADE MES])) * 100,2)  AS 'PERCENTUAL',


	CASE
		WHEN AUX.[QUANTIDADE MES] <= AUX.[VOLUME DE COMPRA] THEN 'VENDA VÁLIDA'
		ELSE 'VENDA INVALIDA'
	END AS 'STATUS VENDA'
FROM
(SELECT TC.NOME,CQ.[ANO/MES], CQ.[QUANTIDADE MES],TC.[VOLUME DE COMPRA]
FROM
(SELECT NF.CPF,SUBSTRING (CONVERT(VARCHAR,NF.DATA,120),1,7) AS 'ANO/MES', SUM (INF.QUANTIDADE) AS 'QUANTIDADE MES' FROM [TABELA DE NOTAS FISCAIS] NF
INNER JOIN [TABELA DE ITENS NOTAS FISCAIS]INF
ON NF.NUMERO = INF.NUMERO
GROUP BY NF.CPF, SUBSTRING (CONVERT(VARCHAR,NF.DATA,120),1,7))CQ
INNER JOIN [TABELA DE CLIENTES]TC
ON TC.CPF = CQ.CPF)AUX
WHERE  AUX.[QUANTIDADE MES] > AUX.[VOLUME DE COMPRA]
ORDER BY AUX.NOME,AUX.[ANO/MES]



--O  dono da esquina do suco pediu para que mostrasse um relatório mostrando,
--qual foi o  faturamento em dinheiro por sabor de produto e também compararmos 
--a participação daquela venda em relação ao total.
--Somente no ano de 2016

----------------- Relatório de Venda por Sabor -----------------------------



SELECT AUX1.SABOR, AUX1.ANO,ROUND (AUX1.FATURAMENTO,2) AS 'FATURAMENTO', CONVERT(VARCHAR,ROUND((AUX1.FATURAMENTO/AUX2.[FATURAMENTO ANUAL])*100,2))+' %' AS 'PERCENTUAL' FROM
(SELECT TP.SABOR, YEAR (NF.DATA) AS 'ANO', SUM (INF.QUANTIDADE * INF.PRECO) AS 'FATURAMENTO' FROM [TABELA DE ITENS NOTAS FISCAIS]INF
INNER JOIN [TABELA DE NOTAS FISCAIS]NF
ON INF.NUMERO = NF.NUMERO
INNER JOIN [TABELA DE PRODUTOS]TP
ON INF.[CODIGO DO PRODUTO] = TP.[CODIGO DO PRODUTO]
WHERE YEAR (NF.DATA) = 2016
GROUP BY TP.SABOR, YEAR (NF.DATA))AUX1
INNER JOIN (SELECT  YEAR (NF.DATA) AS 'ANO', SUM (INF.QUANTIDADE * INF.PRECO) AS 'FATURAMENTO ANUAL' FROM [TABELA DE ITENS NOTAS FISCAIS]INF
INNER JOIN [TABELA DE NOTAS FISCAIS]NF
ON INF.NUMERO = NF.NUMERO
INNER JOIN [TABELA DE PRODUTOS]TP
ON INF.[CODIGO DO PRODUTO] = TP.[CODIGO DO PRODUTO]
WHERE YEAR (NF.DATA) = 2016
GROUP BY YEAR (NF.DATA))AUX2
ON AUX1.ANO = AUX2.ANO
ORDER BY AUX1.FATURAMENTO DESC

----------------------  PASSO A PASSO --------------------------------------------

--PASSO1: PEGANDO AS TABELAS 
SELECT * FROM [TABELA DE PRODUTOS]

SELECT * FROM [TABELA DE NOTAS FISCAIS]

SELECT * FROM [TABELA DE ITENS NOTAS FISCAIS]


--PASSO 2: PEGANDO OS CAMPOS
SELECT TP.SABOR FROM [TABELA DE PRODUTOS]TP

SELECT NF.DATA FROM [TABELA DE NOTAS FISCAIS]NF

SELECT (INF.QUANTIDADE * INF.PRECO) AS 'FATURAMENTO' FROM [TABELA DE ITENS NOTAS FISCAIS]INF


--PASSO 3: JUNTANDO AS TABELAS
SELECT TP.SABOR, NF.DATA,(INF.QUANTIDADE * INF.PRECO) AS 'FATURAMENTO' FROM [TABELA DE ITENS NOTAS FISCAIS]INF
INNER JOIN [TABELA DE NOTAS FISCAIS]NF
ON INF.NUMERO = NF.NUMERO
INNER JOIN [TABELA DE PRODUTOS]TP
ON INF.[CODIGO DO PRODUTO] = TP.[CODIGO DO PRODUTO]


--PASSO 4: FILTRANDO PELA DATA E DANDO NOME AS COLUNAS 
SELECT TP.SABOR, YEAR (NF.DATA) AS 'ANO', (INF.QUANTIDADE * INF.PRECO) AS 'FATURAMENTO' FROM [TABELA DE ITENS NOTAS FISCAIS]INF
INNER JOIN [TABELA DE NOTAS FISCAIS]NF
ON INF.NUMERO = NF.NUMERO
INNER JOIN [TABELA DE PRODUTOS]TP
ON INF.[CODIGO DO PRODUTO] = TP.[CODIGO DO PRODUTO]
WHERE YEAR (NF.DATA) = 2016



--PASSO 5: AGRUPANDO
SELECT TP.SABOR, YEAR (NF.DATA) AS 'ANO', SUM (INF.QUANTIDADE * INF.PRECO) AS 'FATURAMENTO' FROM [TABELA DE ITENS NOTAS FISCAIS]INF
INNER JOIN [TABELA DE NOTAS FISCAIS]NF
ON INF.NUMERO = NF.NUMERO
INNER JOIN [TABELA DE PRODUTOS]TP
ON INF.[CODIGO DO PRODUTO] = TP.[CODIGO DO PRODUTO]
WHERE YEAR (NF.DATA) = 2016
GROUP BY TP.SABOR, YEAR (NF.DATA)


-- PASSO 6: AGRUPANDO O FATURAMENTO ANUAL (TIRO O CAMPO SABOR) 
SELECT  YEAR (NF.DATA) AS 'ANO', SUM (INF.QUANTIDADE * INF.PRECO) AS 'FATURAMENTO' FROM [TABELA DE ITENS NOTAS FISCAIS]INF
INNER JOIN [TABELA DE NOTAS FISCAIS]NF
ON INF.NUMERO = NF.NUMERO
INNER JOIN [TABELA DE PRODUTOS]TP
ON INF.[CODIGO DO PRODUTO] = TP.[CODIGO DO PRODUTO]
WHERE YEAR (NF.DATA) = 2016
GROUP BY YEAR (NF.DATA)




--SELECT'CAMPO1' ,'CAMPO2' FROM [TABELA DE PRODUTOS]

--PASSO 7: INNER JOIN NAS DUAS CONSULTAS 
SELECT * FROM
(SELECT TP.SABOR, YEAR (NF.DATA) AS 'ANO', SUM (INF.QUANTIDADE * INF.PRECO) AS 'FATURAMENTO' FROM [TABELA DE ITENS NOTAS FISCAIS]INF
INNER JOIN [TABELA DE NOTAS FISCAIS]NF
ON INF.NUMERO = NF.NUMERO
INNER JOIN [TABELA DE PRODUTOS]TP
ON INF.[CODIGO DO PRODUTO] = TP.[CODIGO DO PRODUTO]
WHERE YEAR (NF.DATA) = 2016
GROUP BY TP.SABOR, YEAR (NF.DATA))AUX1

INNER JOIN 

(SELECT  YEAR (NF.DATA) AS 'ANO', SUM (INF.QUANTIDADE * INF.PRECO) AS 'FATURAMENTO' FROM [TABELA DE ITENS NOTAS FISCAIS]INF
INNER JOIN [TABELA DE NOTAS FISCAIS]NF
ON INF.NUMERO = NF.NUMERO
INNER JOIN [TABELA DE PRODUTOS]TP
ON INF.[CODIGO DO PRODUTO] = TP.[CODIGO DO PRODUTO]
WHERE YEAR (NF.DATA) = 2016
GROUP BY YEAR (NF.DATA))AUX2

ON AUX1.ANO = AUX2.ANO




-- PASSO 8: MUDANDO O NOME DO FATURAMENTO DO AUX2 PARA 'FATURAMENTO ANUAL'
SELECT AUX1.SABOR, AUX1.ANO,AUX1.FATURAMENTO,AUX2.[FATURAMENTO ANUAL] FROM
(SELECT TP.SABOR, YEAR (NF.DATA) AS 'ANO', SUM (INF.QUANTIDADE * INF.PRECO) AS 'FATURAMENTO' FROM [TABELA DE ITENS NOTAS FISCAIS]INF
INNER JOIN [TABELA DE NOTAS FISCAIS]NF
ON INF.NUMERO = NF.NUMERO
INNER JOIN [TABELA DE PRODUTOS]TP
ON INF.[CODIGO DO PRODUTO] = TP.[CODIGO DO PRODUTO]
WHERE YEAR (NF.DATA) = 2016
GROUP BY TP.SABOR, YEAR (NF.DATA))AUX1
INNER JOIN (SELECT  YEAR (NF.DATA) AS 'ANO', SUM (INF.QUANTIDADE * INF.PRECO) AS 'FATURAMENTO ANUAL' FROM [TABELA DE ITENS NOTAS FISCAIS]INF
INNER JOIN [TABELA DE NOTAS FISCAIS]NF
ON INF.NUMERO = NF.NUMERO
INNER JOIN [TABELA DE PRODUTOS]TP
ON INF.[CODIGO DO PRODUTO] = TP.[CODIGO DO PRODUTO]
WHERE YEAR (NF.DATA) = 2016
GROUP BY YEAR (NF.DATA))AUX2
ON AUX1.ANO = AUX2.ANO


-- PASSO 9: CRIANDO O PERCENTUAL

SELECT AUX1.SABOR, AUX1.ANO,AUX1.FATURAMENTO,(AUX1.FATURAMENTO/AUX2.[FATURAMENTO ANUAL])*100 AS 'PERCENTUAL' FROM
(SELECT TP.SABOR, YEAR (NF.DATA) AS 'ANO', SUM (INF.QUANTIDADE * INF.PRECO) AS 'FATURAMENTO' FROM [TABELA DE ITENS NOTAS FISCAIS]INF
INNER JOIN [TABELA DE NOTAS FISCAIS]NF
ON INF.NUMERO = NF.NUMERO
INNER JOIN [TABELA DE PRODUTOS]TP
ON INF.[CODIGO DO PRODUTO] = TP.[CODIGO DO PRODUTO]
WHERE YEAR (NF.DATA) = 2016
GROUP BY TP.SABOR, YEAR (NF.DATA))AUX1
INNER JOIN (SELECT  YEAR (NF.DATA) AS 'ANO', SUM (INF.QUANTIDADE * INF.PRECO) AS 'FATURAMENTO ANUAL' FROM [TABELA DE ITENS NOTAS FISCAIS]INF
INNER JOIN [TABELA DE NOTAS FISCAIS]NF
ON INF.NUMERO = NF.NUMERO
INNER JOIN [TABELA DE PRODUTOS]TP
ON INF.[CODIGO DO PRODUTO] = TP.[CODIGO DO PRODUTO]
WHERE YEAR (NF.DATA) = 2016
GROUP BY YEAR (NF.DATA))AUX2
ON AUX1.ANO = AUX2.ANO



--PASSO 10: ORDENANDO PELO FATURAMENTO (AUX1)
SELECT AUX1.SABOR, AUX1.ANO,AUX1.FATURAMENTO,(AUX1.FATURAMENTO/AUX2.[FATURAMENTO ANUAL])*100 AS 'PERCENTUAL' FROM
(SELECT TP.SABOR, YEAR (NF.DATA) AS 'ANO', SUM (INF.QUANTIDADE * INF.PRECO) AS 'FATURAMENTO' FROM [TABELA DE ITENS NOTAS FISCAIS]INF
INNER JOIN [TABELA DE NOTAS FISCAIS]NF
ON INF.NUMERO = NF.NUMERO
INNER JOIN [TABELA DE PRODUTOS]TP
ON INF.[CODIGO DO PRODUTO] = TP.[CODIGO DO PRODUTO]
WHERE YEAR (NF.DATA) = 2016
GROUP BY TP.SABOR, YEAR (NF.DATA))AUX1
INNER JOIN (SELECT  YEAR (NF.DATA) AS 'ANO', SUM (INF.QUANTIDADE * INF.PRECO) AS 'FATURAMENTO ANUAL' FROM [TABELA DE ITENS NOTAS FISCAIS]INF
INNER JOIN [TABELA DE NOTAS FISCAIS]NF
ON INF.NUMERO = NF.NUMERO
INNER JOIN [TABELA DE PRODUTOS]TP
ON INF.[CODIGO DO PRODUTO] = TP.[CODIGO DO PRODUTO]
WHERE YEAR (NF.DATA) = 2016
GROUP BY YEAR (NF.DATA))AUX2
ON AUX1.ANO = AUX2.ANO
ORDER BY AUX1.FATURAMENTO DESC


--PASSO 11: CONVERTENDO E ARRENDONDANDO CAMPOS (FINALIZANDO O RELATÓRIO)

SELECT AUX1.SABOR, AUX1.ANO,ROUND (AUX1.FATURAMENTO,2) AS 'FATURAMENTO', CONVERT(VARCHAR,ROUND((AUX1.FATURAMENTO/AUX2.[FATURAMENTO ANUAL])*100,2))+' %' AS 'PERCENTUAL' FROM
(SELECT TP.SABOR, YEAR (NF.DATA) AS 'ANO', SUM (INF.QUANTIDADE * INF.PRECO) AS 'FATURAMENTO' FROM [TABELA DE ITENS NOTAS FISCAIS]INF
INNER JOIN [TABELA DE NOTAS FISCAIS]NF
ON INF.NUMERO = NF.NUMERO
INNER JOIN [TABELA DE PRODUTOS]TP
ON INF.[CODIGO DO PRODUTO] = TP.[CODIGO DO PRODUTO]
WHERE YEAR (NF.DATA) = 2016
GROUP BY TP.SABOR, YEAR (NF.DATA))AUX1
INNER JOIN (SELECT  YEAR (NF.DATA) AS 'ANO', SUM (INF.QUANTIDADE * INF.PRECO) AS 'FATURAMENTO ANUAL' FROM [TABELA DE ITENS NOTAS FISCAIS]INF
INNER JOIN [TABELA DE NOTAS FISCAIS]NF
ON INF.NUMERO = NF.NUMERO
INNER JOIN [TABELA DE PRODUTOS]TP
ON INF.[CODIGO DO PRODUTO] = TP.[CODIGO DO PRODUTO]
WHERE YEAR (NF.DATA) = 2016
GROUP BY YEAR (NF.DATA))AUX2
ON AUX1.ANO = AUX2.ANO
ORDER BY AUX1.FATURAMENTO DESC



SELECT AUX1.SABOR, AUX1.ANO, FORMAT(CONVERT(DECIMAL(15,2),AUX1.FATURAMENTO),'C','PT-BR') AS 'FATURAMENTO', CONVERT(VARCHAR,ROUND((AUX1.FATURAMENTO/AUX2.[FATURAMENTO ANUAL])*100,2))+' %' AS 'PERCENTUAL' FROM
(SELECT TP.SABOR, YEAR (NF.DATA) AS 'ANO', SUM (INF.QUANTIDADE * INF.PRECO) AS 'FATURAMENTO' FROM [TABELA DE ITENS NOTAS FISCAIS]INF
INNER JOIN [TABELA DE NOTAS FISCAIS]NF
ON INF.NUMERO = NF.NUMERO
INNER JOIN [TABELA DE PRODUTOS]TP
ON INF.[CODIGO DO PRODUTO] = TP.[CODIGO DO PRODUTO]
WHERE YEAR (NF.DATA) = 2016
GROUP BY TP.SABOR, YEAR (NF.DATA))AUX1
INNER JOIN (SELECT  YEAR (NF.DATA) AS 'ANO', SUM (INF.QUANTIDADE * INF.PRECO) AS 'FATURAMENTO ANUAL' FROM [TABELA DE ITENS NOTAS FISCAIS]INF
INNER JOIN [TABELA DE NOTAS FISCAIS]NF
ON INF.NUMERO = NF.NUMERO
INNER JOIN [TABELA DE PRODUTOS]TP
ON INF.[CODIGO DO PRODUTO] = TP.[CODIGO DO PRODUTO]
WHERE YEAR (NF.DATA) = 2016
GROUP BY YEAR (NF.DATA))AUX2
ON AUX1.ANO = AUX2.ANO
ORDER BY AUX1.FATURAMENTO DESC



--OUTRA RESPOSTA COM O FORMAT PARA MOEDA E COM DUAS CASAS DECIMAIS E COM DECIMAL APARECENDO O ZERO NA FORMATACAO DO DECIMAL 'X,10'
--DA DOCUMENTACAO MICROSOFT SOBRE O FORMAT 
 			-- FORMAT(<O NUMERO AQUI>, 'N', 'PT-BR') AS 'Number Format' (FORMATO NUMERICO)
            -- FORMAT(<O NUMERO AQUI>, 'G', 'PT-BR') AS 'General Format'  (FORMATO GERAL)
            -- FORMAT<(O NUMERO AQUI>, 'C', 'PT-BR') AS 'Currency Format'  (FORMATO MOEDA)


SELECT AUX1.SABOR, AUX1.ANO, FORMAT(AUX1.FATURAMENTO,'C','PT-BR') AS 'FATURAMENTO', CONVERT(VARCHAR,ROUND((AUX1.FATURAMENTO/AUX2.[FATURAMENTO ANUAL])*100,2))+' %' AS 'PERCENTUAL' FROM
(SELECT TP.SABOR, YEAR (NF.DATA) AS 'ANO', SUM (INF.QUANTIDADE * INF.PRECO) AS 'FATURAMENTO' FROM [TABELA DE ITENS NOTAS FISCAIS]INF
INNER JOIN [TABELA DE NOTAS FISCAIS]NF
ON INF.NUMERO = NF.NUMERO
INNER JOIN [TABELA DE PRODUTOS]TP
ON INF.[CODIGO DO PRODUTO] = TP.[CODIGO DO PRODUTO]
WHERE YEAR (NF.DATA) = 2016
GROUP BY TP.SABOR, YEAR (NF.DATA))AUX1
INNER JOIN (SELECT  YEAR (NF.DATA) AS 'ANO', SUM (INF.QUANTIDADE * INF.PRECO) AS 'FATURAMENTO ANUAL' FROM [TABELA DE ITENS NOTAS FISCAIS]INF
INNER JOIN [TABELA DE NOTAS FISCAIS]NF
ON INF.NUMERO = NF.NUMERO
INNER JOIN [TABELA DE PRODUTOS]TP
ON INF.[CODIGO DO PRODUTO] = TP.[CODIGO DO PRODUTO]
WHERE YEAR (NF.DATA) = 2016
GROUP BY YEAR (NF.DATA))AUX2
ON AUX1.ANO = AUX2.ANO
ORDER BY AUX1.FATURAMENTO DESC


----------------------------- DESAFIO 02 DA AULA 11 ---------------------------------------
--??????????????????? DEIXAR PRA VCS FAZEREM :)