

-- O dono da Esquina do Sucos pediu para que criasse um relatório mostrando qual foi o faturamento em dinheiro por sabor de produto e também que comparasse a participação daquela venda em relação ao total (%). Somente do ano 2016
-- Modifique o segundo relatório feito na aula, mas agora para ver o ranking das vendas por tamanho.
CREATE VIEW TODOS_CAMPOS_2 AS
SELECT P.TAMANHO, P.[CODIGO DO PRODUTO], INF.PREÇO, INF.QUANTIDADE, NF.DATA, NF.NUMERO FROM [dbo].[TABELA DE ITENS NOTAS FISCAIS]INF
INNER JOIN [dbo].[TABELA DE PRODUTOS] P ON INF.[CODIGO DO PRODUTO] = P.[CODIGO DO PRODUTO]
INNER JOIN [dbo].[TABELA DE NOTAS FISCAIS]NF ON INF.NUMERO = NF.NUMERO

CREATE VIEW FATURAMENTO_2 AS
SELECT TAMANHO, YEAR(DATA) AS 'ANO',ROUND( SUM(QUANTIDADE*PREÇO),2) AS 'FATURAMENTO' FROM TODOS_CAMPOS_2
WHERE YEAR(DATA) = 2016
GROUP BY TAMANHO, YEAR(DATA)

CREATE VIEW FATURAMENTO_TOTAL_2 AS
SELECT ANO, SUM(FATURAMENTO) AS 'FATURAMENTO TOTAL' FROM FATURAMENTO_2
GROUP BY ANO

SELECT F.TAMANHO, F.ANO, F.FATURAMENTO, CONCAT(ROUND((F.FATURAMENTO*100/FT.[FATURAMENTO TOTAL]),2),' %' )AS 'PARTICIPAÇÃO' FROM FATURAMENTO_2 F
INNER JOIN FATURAMENTO_TOTAL_2 FT
ON F.ANO = FT.ANO
ORDER BY F.FATURAMENTO DESC