USE ESQUINA_VENDAS
--UNION
SELECT DISTINCT BAIRRO FROM [TABELA DE CLIENTES]

SELECT BAIRRO AS 'BAIRROS' FROM [TABELA DE CLIENTES]
UNION -- JÁ FAZ DISTINCT
SELECT BAIRRO FROM [TABELA DE VENDEDORES]

SELECT BAIRRO AS 'BAIRROS' FROM [TABELA DE CLIENTES]
UNION ALL -- NÃO FAZ DISTINCT
SELECT BAIRRO FROM [TABELA DE VENDEDORES]

SELECT BAIRRO, NOME FROM [TABELA DE CLIENTES]
UNION ALL
SELECT BAIRRO, NOME FROM [TABELA DE VENDEDORES]

SELECT BAIRRO, NOME, 'CLIENTE' AS 'CLIENTE/VENDEDOR' FROM [TABELA DE CLIENTES]
UNION ALL
SELECT BAIRRO, NOME, 'VENDEDOR' AS 'CLIENTE/VENDEDOR' FROM [TABELA DE VENDEDORES]
ORDER BY 3

--END

-- SUBCONSULTA

SELECT NOME, BAIRRO FROM [dbo].[TABELA DE CLIENTES]
WHERE BAIRRO IN (SELECT BAIRRO FROM [dbo].[TABELA DE VENDEDORES])

SELECT A.EMBALAGEM, A.[MAX PREÇO] FROM (SELECT EMBALAGEM, MAX([PRECO DE LISTA]) AS 'MAX PREÇO' FROM [dbo].[TABELA DE PRODUTOS]
GROUP BY EMBALAGEM ) A
WHERE A.[MAX PREÇO] >5

-- USANDO SUBCONSULTA, REPRODUZIR O CÓDIGO ABAIXO
SELECT CPF, COUNT(*) AS 'QTD COMPRAS' FROM [dbo].[TABELA DE NOTAS FISCAIS]
WHERE YEAR(DATA) = 2016
GROUP BY CPF
HAVING COUNT(*) >2000 --SCRIPT SEM SUBCONSULTA

--COM
SELECT A.CPF, COUNT(*) AS 'QTD COMPRAS' FROM(SELECT * FROM [dbo].[TABELA DE NOTAS FISCAIS] WHERE YEAR(DATA) = 2016) A
GROUP BY A.CPF
HAVING COUNT(*) >2000

--COM SUBCONSULTA E JOIN
SELECT C.NOME AS 'NOME CLIENTE', C.CPF, B.[QTD COMPRAS] FROM [dbo].[TABELA DE CLIENTES] C
INNER JOIN (SELECT A.CPF, COUNT(*) AS 'QTD COMPRAS' FROM(SELECT * FROM [dbo].[TABELA DE NOTAS FISCAIS] WHERE YEAR(DATA) = 2016) A
GROUP BY A.CPF
HAVING COUNT(*) >2000) B
ON C.CPF = B.CPF

-- VIEW

CREATE VIEW VW_EMBALAGEM AS 
	SELECT EMBALAGEM, MAX([PRECO DE LISTA]) AS 'MAIOR PREÇO' FROM [dbo].[TABELA DE PRODUTOS]
	GROUP BY EMBALAGEM

SELECT * FROM VW_EMBALAGEM
