USE ESQUINA_VENDAS
CREATE PROCEDURE CriarNotaFiscal
@Data DATE 
AS
	BEGIN
		DECLARE @CLIENTE VARCHAR (20),@VENDEDOR VARCHAR (20),@PRODUTO VARCHAR (20),@NUMERO INT,@IMPOSTO FLOAT,
				@QUANTIDADE INT,@PRECO FLOAT,@NUM_ITENS INT,@CONTADOR INT,@AUX_PRODUTO INT
		DECLARE @LISTA_PRODUTOS TABLE (PRODUTO VARCHAR (20))
		SET @CLIENTE = DBO.ENTIDADEALEATORIA('CLIENTE')
		SET @VENDEDOR = DBO.ENTIDADEALEATORIA('VENDEDOR')
		SELECT @NUMERO = MAX(CONVERT(INT,NUMERO)) + 1 FROM [TABELA DE NOTAS FISCAIS]
		SET @IMPOSTO = 0.18
		SET @NUM_ITENS = DBO.NumeroAleatorio(2,10)
		SET @CONTADOR = 1
		INSERT INTO [TABELA DE NOTAS FISCAIS](CPF,MATRICULA,DATA,NUMERO,IMPOSTO)
		VALUES (@CLIENTE,@VENDEDOR,@DATA,CONVERT(VARCHAR,@NUMERO),@IMPOSTO)
		WHILE @CONTADOR <= @NUM_ITENS
			BEGIN
				SET @PRODUTO = DBO.EntidadeAleatoria('PRODUTO')
				SELECT @AUX_PRODUTO = COUNT (*) FROM @LISTA_PRODUTOS WHERE PRODUTO = @PRODUTO
				IF(@AUX_PRODUTO=0)
					BEGIN
						SET @QUANTIDADE = DBO.NumeroAleatorio(5,100)
						SELECT @PRECO = [PRECO DE LISTA]  FROM [TABELA DE PRODUTOS] 
						WHERE [CODIGO DO PRODUTO] = @PRODUTO
						INSERT INTO [TABELA DE ITENS NOTAS FISCAIS] (NUMERO,[CODIGO DO PRODUTO],QUANTIDADE,PREÇO)
						VALUES (@NUMERO,@PRODUTO,@QUANTIDADE,@PRECO)
						SET @CONTADOR = @CONTADOR + 1
					END
				INSERT INTO @LISTA_PRODUTOS (PRODUTO) VALUES (@PRODUTO)
		END
	END

EXEC CriarNotaFiscal '20210621'


 



 