USE ESQUINA_VENDAS
--CRIAÇÃO PROCEDURE
CREATE PROCEDURE AtualizaImposto  
@MES INT, @ANO INT, @EMBALAGEM VARCHAR (10), @IMPOSTO FLOAT
AS 

  UPDATE NF
  SET NF.IMPOSTO = @IMPOSTO
  FROM [TABELA DE NOTAS FISCAIS] NF
  INNER JOIN [TABELA DE ITENS NOTAS FISCAIS]INF
  ON NF.NUMERO = INF.NUMERO
  INNER JOIN [TABELA DE PRODUTOS]TP
  ON TP.[CODIGO DO PRODUTO] = INF.[CODIGO DO PRODUTO]
  WHERE MONTH(NF.DATA) = @MES AND YEAR (NF.DATA) = @ANO AND TP.EMBALAGEM = @EMBALAGEM

  -- EXECUÇÃO PROCEDURE
  EXEC AtualizaImposto @MES=5, @ANO=2016, @EMBALAGEM='Pet', @IMPOSTO = 0.11


  -- TESTE DA PROCEDURE
 SELECT TP.EMBALAGEM,NF.DATA,NF.IMPOSTO FROM [TABELA DE NOTAS FISCAIS] NF
 INNER JOIN [TABELA DE ITENS NOTAS FISCAIS]INF
 ON NF.NUMERO = INF.NUMERO
 INNER JOIN [TABELA DE PRODUTOS]TP
 ON TP.[CODIGO DO PRODUTO] = INF.[CODIGO DO PRODUTO]
 WHERE MONTH(NF.DATA) = 5 AND YEAR (NF.DATA) = 2016 AND TP.EMBALAGEM = 'Pet'



