
-- TESTINHO AULA 8 
USE ESQUINA_VENDAS

-- EX 1 Monte uma consulta que liste o nome, bairro e cidade ordenando por ordem alfabética pelo nome do cliente --
SELECT [NOME], [BAIRRO], [CIDADE] FROM [dbo].[TABELA DE CLIENTES]
ORDER BY [NOME]

-- EX 2 Listar as notas vendidas e seus respectivos vendedores ordenados pelo bairro do vendedor --
SELECT NF.[NUMERO] AS 'NUMERO DA NOTA FISCAL', V.NOME AS 'VENDEDOR(A)' FROM [dbo].[TABELA DE NOTAS FISCAIS] NF
INNER JOIN [dbo].[TABELA DE VENDEDORES] V
ON NF.MATRICULA = V.MATRICULA
ORDER BY V.BAIRRO

-- EX 3 Liste a menor venda pela Esquina de Suco para cada produto.  (EU ENTENDO COMO MENOR VENDA COMO O MENOR PREÇO DA COMPRA, NÃO A MENOR QUANTIDADE VENDIDA) --
SELECT P.[NOME DO PRODUTO], MIN(INF.[QUANTIDADE]*INF.PREÇO) AS 'MENOR QUANTIDADE VENDIDA' FROM [dbo].[TABELA DE PRODUTOS] P
INNER JOIN [dbo].[TABELA DE ITENS NOTAS FISCAIS] INF
ON P.[CODIGO DO PRODUTO] = INF.[CODIGO DO PRODUTO]
GROUP BY P.[NOME DO PRODUTO]
ORDER BY MIN(INF.[QUANTIDADE]*INF.PREÇO)