USE ESQUINA_VENDAS
			
CREATE FUNCTION [dbo].[FUNCFaturamentoPercentual] (@EMBALAGEM VARCHAR (50)) RETURNS TABLE
AS
	RETURN

			SELECT AUX.EMBALAGEM,AUX.ANO,ROUND(AUX.[FATURAMENTO],2) AS 'FATURAMENTO', CONVERT (VARCHAR,ROUND((AUX.[FATURAMENTO]/AUX1.[FATURAMENTO_ANUAL])*100,2))+ '%' AS 'PERCENTUAL' FROM
			(SELECT TP.[EMBALAGEM], YEAR(NF.DATA) AS 'ANO',SUM (INF.QUANTIDADE*INF.PREÇO) AS 'FATURAMENTO' FROM [TABELA DE ITENS NOTAS FISCAIS]INF
			INNER JOIN [TABELA DE NOTAS FISCAIS]NF
			ON INF.NUMERO = NF.NUMERO 
			INNER JOIN [TABELA DE PRODUTOS]TP
			ON INF.[CODIGO DO PRODUTO] = TP.[CODIGO DO PRODUTO] 
			GROUP BY TP.EMBALAGEM,YEAR(NF.DATA))AUX
			INNER JOIN
			(SELECT YEAR(NF.DATA) AS 'ANO',SUM (INF.QUANTIDADE*INF.PREÇO) AS 'FATURAMENTO_ANUAL' FROM [TABELA DE ITENS NOTAS FISCAIS]INF
			INNER JOIN [TABELA DE NOTAS FISCAIS]NF
			ON INF.NUMERO = NF.NUMERO 
			INNER JOIN [TABELA DE PRODUTOS]TP
			ON INF.[CODIGO DO PRODUTO] = TP.[CODIGO DO PRODUTO]
			GROUP BY YEAR(NF.DATA))AUX1
			ON AUX.ANO = AUX1.ANO
			WHERE AUX.EMBALAGEM = @EMBALAGEM
