USE ESQUINA_VENDAS
DECLARE @VOLUMECOMPRA FLOAT, @CPF VARCHAR(11) , @MES INT, @ANO INT, @QTDCOMPRA INT, @NOME VARCHAR(100)
SET @MES = 12
SET @ANO = 2016
SET @CPF = '1471156710'
SELECT @VOLUMECOMPRA = C.[VOLUME DE COMPRA], @QTDCOMPRA = SUM(INF.QUANTIDADE), @NOME = C.NOME FROM [dbo].[TABELA DE NOTAS FISCAIS] NF
INNER JOIN [dbo].[TABELA DE CLIENTES] C ON C.CPF = NF.CPF
INNER JOIN [dbo].[TABELA DE ITENS NOTAS FISCAIS] INF ON NF.NUMERO = INF.NUMERO
WHERE MONTH(NF.DATA) = @MES AND YEAR(NF.DATA) = @ANO AND C.CPF = @CPF
GROUP BY C.[VOLUME DE COMPRA], C.NOME

IF(@VOLUMECOMPRA > @QTDCOMPRA)
	BEGIN
		PRINT 'O cliente '+ @NOME + ' não ultrapassou o seu volume de compra neste periodo'
		PRINT 'Nome: '+ @NOME
		PRINT 'Volume de compras: '+ CONVERT(VARCHAR, @VOLUMECOMPRA) + ' Quantidade comprada: ' + CONVERT(VARCHAR, @QTDCOMPRA )
		PRINT 'MÊS/ANO: ' + CONVERT(VARCHAR, @MES) + '/' + CONVERT(VARCHAR, @ANO)
	END
ELSE
	BEGIN
		PRINT 'O cliente '+ @NOME + ' ultrapassou o seu volume de compra neste periodo'
		PRINT 'Nome: '+ @NOME
		PRINT 'Volume de compras: '+ CONVERT(VARCHAR, @VOLUMECOMPRA) + ' Quantidade comprada: ' + CONVERT(VARCHAR, @QTDCOMPRA )
		PRINT 'MÊS/ANO: ' + CONVERT(VARCHAR, @MES) + '/' + CONVERT(VARCHAR, @ANO)
	END
