CREATE PROCEDURE NumNotasSP
@DATA_INICIAL  DATE,
@DATA_FINAL DATE,
@NUMNOTAS  INT OUTPUT
AS
BEGIN
    DECLARE @I INT 
	SET @NUMNOTAS = 0
	
	WHILE @DATA_INICIAL <= @DATA_FINAL
			BEGIN
			 
				 SELECT @I = COUNT(*) FROM [TABELA DE NOTAS FISCAIS] 
				 WHERE [DATA] = @DATA_INICIAL
			 
				SET @NUMNOTAS = @NUMNOTAS+@I
				SELECT @DATA_INICIAL = DATEADD(DAY,1,@DATA_INICIAL)	
			
			END
END
GO

--TESTE DA PROCEDURE
DECLARE @NUMNOTAS INT
DECLARE @D_INICIAL DATE
DECLARE @D_FINAL DATE

SET @NUMNOTAS = 0
SET @D_INICIAL = '20160101'
SET @D_FINAL = '20161231'

EXEC NumNotasSP @DATA_INICIAL = @D_INICIAL, @DATA_FINAL = @D_FINAL, @NUMNOTAS=@NUMNOTAS OUTPUT

PRINT CONCAT('NUMERO DE NOTAS ENTRE ' , CONVERT (VARCHAR, @D_INICIAL) + ' E ' , CONVERT (VARCHAR, @D_FINAL) + ' SÃO: ' , CONVERT (VARCHAR,@NUMNOTAS) + ' NOTAS' )

