USE ESQUINA_VENDAS

--1 - Crie uma consulta que mostre o nome do vendedor, o número da nota fiscal, 
-- o valor faturado da nota e quanto o vendedor ganhou de comissão para cada nota fiscal.
SELECT V.NOME AS 'NOME DO VENDEDOR', NF.NUMERO AS 'NUMERO DA NOTA FISCAL', SUM((INF.QUANTIDADE*INF.PREÇO)) AS 'VALOR FATURADO DA NOTA', SUM((INF.QUANTIDADE*INF.PREÇO)*V.[PERCENTUAL COMISSAO]) AS 'COMISSÃO DO VENDEDOR SOBRE A COMPRA' FROM [dbo].[TABELA DE NOTAS FISCAIS] NF 
INNER JOIN [dbo].[TABELA DE VENDEDORES] V ON NF.MATRICULA = V.MATRICULA
INNER JOIN [dbo].[TABELA DE ITENS NOTAS FISCAIS] INF  ON INF.NUMERO = NF.NUMERO
GROUP BY V.NOME, NF.NUMERO
ORDER BY V.NOME
