USE ESQUINA_VENDAS

-- Queremos construir um SQL cujo resultado seja, para cada cliente: 
-- "O cliente João da Silva faturou 120000 no ano de 2016". Somente para o ano de 2016. 
SELECT CONCAT('O cliente ', C.NOME, ' faturou ', B.FATURA ,' no ano de ', B.ANO ) AS 'FRASE DO FATURAMENTO' FROM [dbo].[TABELA DE CLIENTES] C
FULL JOIN (SELECT YEAR(NF.DATA) AS 'ANO', C.NOME, FORMAT(SUM(INF.[QUANTIDADE]*INF.[PREÇO]), '#,###.##','PT-BR') AS 'FATURA'FROM [dbo].[TABELA DE NOTAS FISCAIS] NF
RIGHT JOIN [dbo].[TABELA DE CLIENTES] C ON C.CPF = NF.CPF
INNER JOIN [dbo].[TABELA DE ITENS NOTAS FISCAIS] INF ON INF.NUMERO = NF.NUMERO
WHERE YEAR(NF.DATA)=2016
GROUP BY C.NOME, YEAR(NF.DATA)) B
ON C.NOME = B.NOME
ORDER BY C.NOME