USE ESQUINA_VENDAS

-- 1 - Na aula, construímos um relatório que apresentou os clientes que tiveram vendas inválidas. 
-- Complemente este relatório, listando somente os que tiveram vendas inválidas e 
--calculando a diferença entre o limite de venda máximo e o realizado, em percentuais. 
CREATE VIEW A AS
SELECT NF.CPF, SUBSTRING(CONVERT(VARCHAR, NF.DATA,120),1,7) AS 'ANO/MÊS', SUM(INF.QUANTIDADE) AS 'QUANTIDADE MÊS' FROM [dbo].[TABELA DE NOTAS FISCAIS]NF
INNER JOIN [dbo].[TABELA DE ITENS NOTAS FISCAIS]INF
ON NF.NUMERO = INF.NUMERO	
GROUP BY NF.CPF, SUBSTRING(CONVERT(VARCHAR, NF.DATA,120),1,7)

CREATE VIEW B AS
SELECT C.NOME, A.[ANO/MÊS], A.[QUANTIDADE MÊS], C.[VOLUME DE COMPRA],
CASE
		WHEN A.[QUANTIDADE MÊS] > C.[VOLUME DE COMPRA] THEN 'VENDA INVÁLIDA' 
		ELSE 'VENDA VÁLIDA'
	END AS 'CLASSIFICAÇÃO'
FROM [dbo].[TABELA DE CLIENTES] C
INNER JOIN A
ON C.CPF = A.CPF


SELECT B.NOME ,B.[ANO/MÊS],B.[QUANTIDADE MÊS], B.[VOLUME DE COMPRA], B.CLASSIFICAÇÃO, (1-(B.[VOLUME DE COMPRA]/B.[QUANTIDADE MÊS]))*100 AS 'DIFERENÇA EM PERCENTUAL'
FROM B
WHERE B.CLASSIFICAÇÃO = 'VENDA INVÁLIDA' 
ORDER BY B.NOME, B.[ANO/MÊS]