CREATE PROCEDURE InclusaoVendedor02
@MATRICULA AS VARCHAR(5), @NOME AS VARCHAR(100), @PERCENTUAL AS FLOAT,
@DATAADMISSAO AS DATE, @FERIAS AS BIT, @BAIRRO AS VARCHAR(50),
@MENSAGEM VARCHAR (MAX) OUTPUT
AS
BEGIN
  BEGIN TRY
		INSERT INTO [TABELA DE VENDEDORES] (MATRICULA, NOME, [PERCENTUAL COMISSAO], [DATA DE ADMISSAO],
		FERIAS, BAIRRO)
		VALUES (@MATRICULA, @NOME, @PERCENTUAL, @DATAADMISSAO, @FERIAS, @BAIRRO)

  END TRY

  BEGIN CATCH

		SET @MENSAGEM = 'Houve um erro número: '+ CONVERT (VARCHAR, @@ERROR)

  END CATCH

END
-- TESTE DA PROCEDURE
DECLARE @ERRO VARCHAR (MAX)

EXEC InclusaoVendedor02'00238', 'Pericles Alves', 0.11, '20160821', 0, 'Santo Amaro', @MENSAGEM = @ERRO OUTPUT
IF @ERRO <> ''
 PRINT @ERRO
