CREATE PROCEDURE InclusaoVendedor01
@MATRICULA AS VARCHAR(5), @NOME AS VARCHAR(100), @PERCENTUAL AS FLOAT,
@DATAADMISSAO AS DATE, @FERIAS AS BIT, @BAIRRO AS VARCHAR(50),
@ERRO INT OUTPUT
AS
BEGIN
	INSERT INTO [TABELA DE VENDEDORES] (MATRICULA, NOME, [PERCENTUAL COMISSAO], [DATA DE ADMISSAO],
	FERIAS, BAIRRO)
	VALUES (@MATRICULA, @NOME, @PERCENTUAL, @DATAADMISSAO, @FERIAS, @BAIRRO)
	SELECT @ERRO = @@ERROR
END

-- TESTE DA PROCEDURE
DECLARE @ERRO INT

EXEC InclusaoVendedor01 '00238', 'Pericles Alves', 0.11, '20160821', 0, 'Santo Amaro', @ERRO = 
@ERRO OUTPUT
IF @ERRO <> 0
 PRINT 'Houve um erro de código: ' + CONVERT(VARCHAR(30), @ERRO) 
