CREATE DATABASE  [ESQUINA_VENDAS]

-------------------------------------------------
USE [ESQUINA_VENDAS]

CREATE TABLE [TABELA DE PRODUTOS](
    [CODIGO DO PRODUTO] [VARCHAR](10),
    [NOME DO PRODUTO][VARCHAR](50),
    [EMBALAGEM][VARCHAR](20),
    [TAMANHO][VARCHAR](10),
    [SABOR][VARCHAR](20),
    [PRECO DE LISTA][SMALLMONEY],
    
)

--------------------------------------------------

USE [ESQUINA_VENDAS]

CREATE TABLE [TABELA DE CLIENTES]
( [CPF] [VARCHAR] (11) ,
[NOME] [VARCHAR] (100) ,
[ENDERECO] [VARCHAR] (150) ,
[COMPLEMENTO] [VARCHAR] (150) ,
[BAIRRO] [VARCHAR] (50) ,
[CIDADE] [VARCHAR] (50) ,
[ESTADO] [VARCHAR] (2) ,
[CEP] [VARCHAR] (8) ,
[DATA DE NASCIMENTO] [DATE],
[IDADE] [SMALLINT],
[SEXO] [VARCHAR] (1) ,
[LIMITE DE CREDITO] [MONEY] ,
[VOLUME DE COMPRA] [FLOAT] ,
[PRIMEIRA COMPRA] [BIT] )

-------------------------------------------------

USE [ESQUINA_VENDAS]

CREATE TABLE [TABELA DE VENDEDORES]
( [MATRICULA] varchar(5),
[NOME] varchar(100),
[PERCENTUAL COMISSAO] float)

-------------------------------------------------




--------------------Inserts-----------------------

--INSERINDO REGISTROS NA TABELA DE VENDEDORES
USE [ESQUINA_VENDAS]


INSERT INTO [TABELA DE VENDEDORES]
([MATRICULA], [NOME], [PERCENTUAL COMISSAO])
VALUES
('00122','Joabe da Silva Freitas',0.10)

INSERT INTO [TABELA DE VENDEDORES]
([MATRICULA], [NOME], [PERCENTUAL COMISSAO])
VALUES
('00133','Marly dos Santos Gama',0.8)

INSERT INTO [TABELA DE VENDEDORES]
([MATRICULA], [NOME], [PERCENTUAL COMISSAO])
VALUES
('00144','Bruno César Brandão',0.5)

INSERT INTO [TABELA DE VENDEDORES]
([MATRICULA], [NOME], [PERCENTUAL COMISSAO])
VALUES
('00155','Roberta Martins',0.11)

INSERT INTO [TABELA DE VENDEDORES]
([MATRICULA], [NOME], [PERCENTUAL COMISSAO])
VALUES
('00166','Pericles Alves',0.07)

-------------------------------------------------------

--INSERINDO REGISTROS NA TABELA DE PRODUTOS

USE [ESQUINA_VENDAS]

INSERT INTO [TABELA DE PRODUTOS]
([CODIGO DO PRODUTO],[NOME DO PRODUTO],[EMBALAGEM],[TAMANHO],[SABOR], [PRECO DE LISTA])
  VALUES 
  ('1040107','Light - 350 ml - Melancia','Lata','350 ml','Melancia',4.56),
   ('1037797','Clean - 2 Litros - Laranja','PET','2 Litros','Laranja',16.01),
    ('1000889','Sabor da Montanha - 700 ml - Uva','Garrafa','700 ml','Uva',6.31),
     ('1004327','Videira do Campo - 1,5 Litros - Melancia','PET','1,5 Litros','Melancia',19.51),
      ('1088126','Linha Citros - 1 Litro - Limão','PET','1 Litro','Limão',7.00),
       ('544931','Frescor do Verão - 350 ml - Limão','Lata','350 ml','Limão',2.46),
        ('1078680','Frescor do Verão - 470 ml - Manga','Garrafa','470 ml','Manga',5.18)







--------------------------------------- Aula 5 – Chave Primária e manipulando outros tipos de dados -----------------------------------------


INSERT INTO [TABELA DE PRODUTOS]([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA])
VALUES('788975', 'Pedaços de Frutas - 1,5 Litros - Maça', 'PET', '1,5 Litros', 'Maça', 18.01)

INSERT INTO [TABELA DE PRODUTOS]([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA])
VALUES('788975', 'Pedaços de Frutas - 1,5 Litros - Maça', 'PET', '1,5 Litros', 'Maça', 18.01)



DROP TABLE [TABELA DE PRODUTOS]


CREATE TABLE [TABELA DE PRODUTOS](
    [CODIGO DO PRODUTO] [VARCHAR](10),
    [NOME DO PRODUTO][VARCHAR](50),
    [EMBALAGEM][VARCHAR](20),
    [TAMANHO][VARCHAR](10),
    [SABOR][VARCHAR](20),
    [PREÇO DE LISTA][SMALLMONEY],
    PRIMARY KEY  ([CODIGO DO PRODUTO])
    
)


--INSERINDO REGISTROS NA TABELA DE PRODUTOS

USE [ESQUINA_VENDAS]

INSERT INTO [TABELA DE PRODUTOS]
([CODIGO DO PRODUTO],[NOME DO PRODUTO],[EMBALAGEM],[TAMANHO],[SABOR], [PRECO DE LISTA])
  VALUES 
  ('1040107','Light - 350 ml - Melancia','Lata','350 ml','Melancia',4.56),
  ('1037797','Clean - 2 Litros - Laranja','PET','2 Litros','Laranja',16.01),
  ('1000889','Sabor da Montanha - 700 ml - Uva','Garrafa','700 ml','Uva',6.31),
  ('1004327','Videira do Campo - 1,5 Litros - Melancia','PET','1,5 Litros','Melancia',19.51),
  ('1088126','Linha Citros - 1 Litro - Limão','PET','1 Litro','Limão',7.00),
  ('544931','Frescor do Verão - 350 ml - Limão','Lata','350 ml','Limão',2.46),
  ('1078680','Frescor do Verão - 470 ml - Manga','Garrafa','470 ml','Manga',5.18)




INSERT INTO [TABELA DE PRODUTOS]([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PREÇO DE LISTA])
VALUES('788975', 'Pedaços de Frutas - 1,5 Litros - Maça', 'PET', '1,5 Litros', 'Maça', 18.01)

-------------------------------- DESAFIO 1 DA AULA 5 ----------------------------------------------------------

DROP TABLE [TABELA DE CLIENTES]

CREATE TABLE [TABELA DE CLIENTES]
( [CPF] [VARCHAR] (11) ,
[NOME] [VARCHAR] (100) ,
[ENDERECO] [VARCHAR] (150) ,
[COMPLEMENTO] [VARCHAR] (150) ,
[BAIRRO] [VARCHAR] (50) ,
[CIDADE] [VARCHAR] (50) ,
[ESTADO] [VARCHAR] (2) ,
[CEP] [VARCHAR] (8) ,
[DATA DE NASCIMENTO] [DATE],
[IDADE] [SMALLINT],
[SEXO] [VARCHAR] (1) ,
[LIMITE DE CREDITO] [MONEY] ,
[VOLUME DE COMPRA] [FLOAT] ,
[PRIMEIRA COMPRA] [BIT],
PRIMARY KEY ([CPF])
)



---------------- DESAFIO 2 (MASTER) DA AULA 5 -------------------------------------

DROP TABLE [TABELA DE VENDEDORES]



CREATE TABLE [TABELA DE VENDEDORES]
( [MATRICULA] [VARCHAR](5),
[NOME] [VARCHAR](100),
[PERCENTUAL COMISSAO] [FLOAT],
[DATA DE ADMISSAO][DATE],
[FERIAS][BIT]
PRIMARY KEY ([MATRICULA])
)


INSERT INTO [TABELA DE VENDEDORES]
([MATRICULA], [NOME], [PERCENTUAL COMISSAO],[DATA DE ADMISSAO],[FERIAS])
VALUES
('00133','Marly dos Santos Gama',0.08,'15/08/2014',0)

INSERT INTO [TABELA DE VENDEDORES]
([MATRICULA], [NOME], [PERCENTUAL COMISSAO],[DATA DE ADMISSAO],[FERIAS])
VALUES
('00144','Bruno César Brandão',0.05,'15/08/2016',1)

INSERT INTO [TABELA DE VENDEDORES]
([MATRICULA], [NOME], [PERCENTUAL COMISSAO],[DATA DE ADMISSAO],[FERIAS])
VALUES
('00155','Roberta Serra',0.11,'15/08/2018',0)

INSERT INTO [TABELA DE VENDEDORES]
([MATRICULA], [NOME], [PERCENTUAL COMISSAO],[DATA DE ADMISSAO],[FERIAS])
VALUES
('00166','Pericles Alves',0.11,'15/08/2019',1)



INSERT INTO [TABELA DE CLIENTES] 
(	[CPF],
	[NOME],
	[ENDERECO],
	[COMPLEMENTO],
	[BAIRRO],
	[CIDADE],
	[ESTADO],
	[CEP],
	[DATA DE NASCIMENTO],
	[IDADE],
	[SEXO],
	[LIMITE DE CREDITO],
	[VOLUME DE COMPRA],
	[PRIMEIRA COMPRA]) 
VALUES 
(	
	'51073366200',
	'Márcio Ladislau Freitas',
	'R. Dois de Fevereiro',
	'',
	'Água Santa',
	'Rio de Janeiro',
	'RJ',
	'22000000',
	--'2000-02-12',
	'12/31/2000',
	18,
	'M',
	100000,
	200000,
	1
)



  DELETE FROM [TABELA DE CLIENTES]
  WHERE [CPF] = '51073366200'



------------------------------------------------------Aula 06 ------------------------------------------------


USE [ESQUINA_VENDAS]

DROP TABLE [TABELA DE CLIENTES]

CREATE TABLE [TABELA DE CLIENTES](
	[CPF] [VARCHAR](11) ,
	[NOME] [VARCHAR](100) ,
	[ENDERECO] [VARCHAR](150) ,
	[COMPLEMENTO] [VARCHAR](150) ,
	[BAIRRO] [VARCHAR](50) ,
	[CIDADE] [VARCHAR](50) ,
	[ESTADO] [VARCHAR](2) ,
	[CEP] [VARCHAR](8) ,
	[DATA DE NASCIMENTO] [DATE] ,
	[IDADE] [SMALLINT ] ,
	[SEXO] [VARCHAR](1) ,
	[LIMITE DE CREDITO] [MONEY] ,
	[VOLUME DE COMPRA] [FLOAT] ,
	[PRIMEIRA COMPRA] [BIT] ,
 	PRIMARY KEY ([CPF])
)


INSERT INTO [TABELA DE CLIENTES] ([CPF],[NOME],[ENDERECO],[COMPLEMENTO],[BAIRRO],[CIDADE],[ESTADO],[CEP],[DATA DE NASCIMENTO],[IDADE],[SEXO],[LIMITE DE CREDITO],[VOLUME DE COMPRA],[PRIMEIRA COMPRA]) VALUES ('19290992743','Fernando Cavalcante','R. Dois de Fevereiro','','Água Santa','Rio de Janeiro','RJ','22000000','2000-02-12',18,'M',100000,200000,1)
INSERT INTO [TABELA DE CLIENTES] ([CPF],[NOME],[ENDERECO],[COMPLEMENTO],[BAIRRO],[CIDADE],[ESTADO],[CEP],[DATA DE NASCIMENTO],[IDADE],[SEXO],[LIMITE DE CREDITO],[VOLUME DE COMPRA],[PRIMEIRA COMPRA]) VALUES ('2600586709','César Teixeira','Rua Conde de Bonfim','','Tijuca','Rio de Janeiro','RJ','22020001','2000-03-12',18,'M',120000,220000,0)
INSERT INTO [TABELA DE CLIENTES] ([CPF],[NOME],[ENDERECO],[COMPLEMENTO],[BAIRRO],[CIDADE],[ESTADO],[CEP],[DATA DE NASCIMENTO],[IDADE],[SEXO],[LIMITE DE CREDITO],[VOLUME DE COMPRA],[PRIMEIRA COMPRA]) VALUES ('95939180787','Fábio Carvalho','R. dos Jacarandás da Península','','Barra da Tijuca','Rio de Janeiro','RJ','22002020','1992-01-05',16,'M',90000,180000,1)
INSERT INTO [TABELA DE CLIENTES] ([CPF],[NOME],[ENDERECO],[COMPLEMENTO],[BAIRRO],[CIDADE],[ESTADO],[CEP],[DATA DE NASCIMENTO],[IDADE],[SEXO],[LIMITE DE CREDITO],[VOLUME DE COMPRA],[PRIMEIRA COMPRA]) VALUES ('9283760794','Edson Meilelles','R. Pinto de Azevedo','','Cidade Nova','Rio de Janeiro','RJ','22002002','1995-10-07',22,'M',150000,250000,1)
INSERT INTO [TABELA DE CLIENTES] ([CPF],[NOME],[ENDERECO],[COMPLEMENTO],[BAIRRO],[CIDADE],[ESTADO],[CEP],[DATA DE NASCIMENTO],[IDADE],[SEXO],[LIMITE DE CREDITO],[VOLUME DE COMPRA],[PRIMEIRA COMPRA]) VALUES ('7771579779','Marcelo Mattos','R. Eduardo Luís Lopes','','Brás','São Paulo','SP','88202912','1992-03-25',25,'M',120000,200000,1)
INSERT INTO [TABELA DE CLIENTES] ([CPF],[NOME],[ENDERECO],[COMPLEMENTO],[BAIRRO],[CIDADE],[ESTADO],[CEP],[DATA DE NASCIMENTO],[IDADE],[SEXO],[LIMITE DE CREDITO],[VOLUME DE COMPRA],[PRIMEIRA COMPRA]) VALUES ('5576228758','Petra Oliveira','R. Benício de Abreu','','Lapa','São Paulo','SP','88192029','1995-11-14',22,'F',70000,160000,1)
INSERT INTO [TABELA DE CLIENTES] ([CPF],[NOME],[ENDERECO],[COMPLEMENTO],[BAIRRO],[CIDADE],[ESTADO],[CEP],[DATA DE NASCIMENTO],[IDADE],[SEXO],[LIMITE DE CREDITO],[VOLUME DE COMPRA],[PRIMEIRA COMPRA]) VALUES ('8502682733','Valdeci da Silva','R. Srg. Édison de Oliveira','','Jardins','São Paulo','SP','82122020','1995-10-07',22,'M',110000,190000,0)
INSERT INTO [TABELA DE CLIENTES] ([CPF],[NOME],[ENDERECO],[COMPLEMENTO],[BAIRRO],[CIDADE],[ESTADO],[CEP],[DATA DE NASCIMENTO],[IDADE],[SEXO],[LIMITE DE CREDITO],[VOLUME DE COMPRA],[PRIMEIRA COMPRA]) VALUES ('1471156710','Érica Carvalho','R. Iriquitia','','Jardins','São Paulo','SP','80012212','1990-09-01',27,'F',170000,245000,0)
INSERT INTO [TABELA DE CLIENTES] ([CPF],[NOME],[ENDERECO],[COMPLEMENTO],[BAIRRO],[CIDADE],[ESTADO],[CEP],[DATA DE NASCIMENTO],[IDADE],[SEXO],[LIMITE DE CREDITO],[VOLUME DE COMPRA],[PRIMEIRA COMPRA]) VALUES ('3623344710','Marcos Nougeuira','Av. Pastor Martin Luther King Junior','','Inhauma','Rio de Janeiro','RJ','22002012','1995-01-13',23,'M',110000,220000,1)
INSERT INTO [TABELA DE CLIENTES] ([CPF],[NOME],[ENDERECO],[COMPLEMENTO],[BAIRRO],[CIDADE],[ESTADO],[CEP],[DATA DE NASCIMENTO],[IDADE],[SEXO],[LIMITE DE CREDITO],[VOLUME DE COMPRA],[PRIMEIRA COMPRA]) VALUES ('50534475787','Abel Silva ','Rua Humaitá','','Humaitá','Rio de Janeiro','RJ','22000212','1995-09-11',22,'M',170000,260000,0)
INSERT INTO [TABELA DE CLIENTES] ([CPF],[NOME],[ENDERECO],[COMPLEMENTO],[BAIRRO],[CIDADE],[ESTADO],[CEP],[DATA DE NASCIMENTO],[IDADE],[SEXO],[LIMITE DE CREDITO],[VOLUME DE COMPRA],[PRIMEIRA COMPRA]) VALUES ('5840119709','Gabriel Araujo','R. Manuel de Oliveira','','Santo Amaro','São Paulo','SP','80010221','1985-03-16',32,'M',140000,210000,1)
INSERT INTO [TABELA DE CLIENTES] ([CPF],[NOME],[ENDERECO],[COMPLEMENTO],[BAIRRO],[CIDADE],[ESTADO],[CEP],[DATA DE NASCIMENTO],[IDADE],[SEXO],[LIMITE DE CREDITO],[VOLUME DE COMPRA],[PRIMEIRA COMPRA]) VALUES ('94387575700','Walber Lontra','R. Cel. Almeida','','Piedade','Rio de Janeiro','RJ','22000201','1989-06-20',28,'M',60000,120000,1)
INSERT INTO [TABELA DE CLIENTES] ([CPF],[NOME],[ENDERECO],[COMPLEMENTO],[BAIRRO],[CIDADE],[ESTADO],[CEP],[DATA DE NASCIMENTO],[IDADE],[SEXO],[LIMITE DE CREDITO],[VOLUME DE COMPRA],[PRIMEIRA COMPRA]) VALUES ('8719655770','Carlos Eduardo','Av. Gen. Guedes da Fontoura','','Jardins','São Paulo','SP','81192002','1983-12-20',34,'M',200000,240000,0)
INSERT INTO [TABELA DE CLIENTES] ([CPF],[NOME],[ENDERECO],[COMPLEMENTO],[BAIRRO],[CIDADE],[ESTADO],[CEP],[DATA DE NASCIMENTO],[IDADE],[SEXO],[LIMITE DE CREDITO],[VOLUME DE COMPRA],[PRIMEIRA COMPRA]) VALUES ('5648641702','Paulo César Mattos','Rua Hélio Beltrão','','Tijuca','Rio de Janeiro','RJ','21002020','1991-08-30',26,'M',120000,220000,0)
INSERT INTO [TABELA DE CLIENTES] ([CPF],[NOME],[ENDERECO],[COMPLEMENTO],[BAIRRO],[CIDADE],[ESTADO],[CEP],[DATA DE NASCIMENTO],[IDADE],[SEXO],[LIMITE DE CREDITO],[VOLUME DE COMPRA],[PRIMEIRA COMPRA]) VALUES ('492472718','Eduardo Jorge','R. Volta Grande','','Tijuca','Rio de Janeiro','RJ','22012002','1994-07-19',23,'M',75000,95000,1)

DROP TABLE [TABELA DE PRODUTOS]

CREATE TABLE [TABELA DE PRODUTOS](
	[CODIGO DO PRODUTO] [VARCHAR](10),
	[NOME DO PRODUTO] [VARCHAR](50),
	[EMBALAGEM] [VARCHAR](20),
	[TAMANHO] [VARCHAR](10),
	[SABOR] [VARCHAR](20),
	[PRECO DE LISTA] [SMALLMONEY],
	PRIMARY KEY ([CODIGO DO PRODUTO])
)


INSERT INTO [TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES ('1040107','Light - 350 ml - Melancia','Lata','350 ml','Melancia',4.555)
INSERT INTO [TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES ('1037797','Clean - 2 Litros - Laranja','PET','2 Litros','Laranja',16.008)
INSERT INTO [TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES ('1000889','Sabor da Montanha - 700 ml - Uva','Garrafa','700 ml','Uva',6.309)
INSERT INTO [TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES ('1004327','Videira do Campo - 1,5 Litros - Melancia','PET','1,5 Litros','Melancia',19.51)
INSERT INTO [TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES ('1088126','Linha Citros - 1 Litro - Limão','PET','1 Litro','Limão',7.004)
INSERT INTO [TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES ('544931','Frescor do Verão - 350 ml - Limão','Lata','350 ml','Limão',2.4595)
INSERT INTO [TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES ('1078680','Frescor do Verão - 470 ml - Manga','Garrafa','470 ml','Manga',5.1795)
INSERT INTO [TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES ('1042712','Linha Citros - 700 ml - Limão','Garrafa','700 ml','Limão',4.904)
INSERT INTO [TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES ('788975','Pedaços de Frutas - 1,5 Litros - Maça','PET','1,5 Litros','Maça',18.011)
INSERT INTO [TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES ('1002767','Videira do Campo - 700 ml - Cereja/Maça','Garrafa','700 ml','Cereja/Maça',8.41)
INSERT INTO [TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES ('231776','Festival de Sabores - 700 ml - Açai','Garrafa','700 ml','Açai',13.312)
INSERT INTO [TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES ('479745','Clean - 470 ml - Laranja','Garrafa','470 ml','Laranja',3.768)
INSERT INTO [TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES ('1051518','Frescor do Verão - 470 ml - Limão','Garrafa','470 ml','Limão',3.2995)
INSERT INTO [TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES ('1101035','Linha Refrescante - 1 Litro - Morango/Limão','PET','1 Litro','Morango/Limão',9.0105)
INSERT INTO [TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES ('229900','Pedaços de Frutas - 350 ml - Maça','Lata','350 ml','Maça',4.211)
INSERT INTO [TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES ('1086543','Linha Refrescante - 1 Litro - Manga','PET','1 Litro','Manga',11.0105)
INSERT INTO [TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES ('695594','Festival de Sabores - 1,5 Litros - Açai','PET','1,5 Litros','Açai',28.512)
INSERT INTO [TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES ('838819','Clean - 1,5 Litros - Laranja','PET','1,5 Litros','Laranja',12.008)
INSERT INTO [TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES ('326779','Linha Refrescante - 1,5 Litros - Manga','PET','1,5 Litros','Manga',16.5105)
INSERT INTO [TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES ('520380','Pedaços de Frutas - 1 Litro - Maça','PET','1 Litro','Maça',12.011)
INSERT INTO [TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES ('1041119','Linha Citros - 700 ml - Lima/Limão','Garrafa','700 ml','Lima/Limão',4.904)
INSERT INTO [TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES ('243083','Festival de Sabores - 1,5 Litros - Maracujá','PET','1,5 Litros','Maracujá',10.512)
INSERT INTO [TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES ('394479','Sabor da Montanha - 700 ml - Cereja','Garrafa','700 ml','Cereja',8.409)
INSERT INTO [TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES ('746596','Light - 1,5 Litros - Melancia','PET','1,5 Litros','Melancia',19.505)
INSERT INTO [TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES ('773912','Clean - 1 Litro - Laranja','PET','1 Litro','Laranja',8.008)
INSERT INTO [TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES ('826490','Linha Refrescante - 700 ml - Morango/Limão','Garrafa','700 ml','Morango/Limão',6.3105)
INSERT INTO [TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES ('723457','Festival de Sabores - 700 ml - Maracujá','Garrafa','700 ml','Maracujá',4.912)
INSERT INTO [TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES ('812829','Clean - 350 ml - Laranja','Lata','350 ml','Laranja',2.808)
INSERT INTO [TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES ('290478','Videira do Campo - 350 ml - Melancia','Lata','350 ml','Melancia',4.56)
INSERT INTO [TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES ('783663','Sabor da Montanha - 700 ml - Morango','Garrafa','700 ml','Morango',7.709)
INSERT INTO [TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES ('235653','Frescor do Verão - 350 ml - Manga','Lata','350 ml','Manga',3.8595)
INSERT INTO [TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES ('1002334','Linha Citros - 1 Litro - Lima/Limão','PET','1 Litro','Lima/Limão',7.004)
INSERT INTO [TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES ('1013793','Videira do Campo - 2 Litros - Cereja/Maça','PET','2 Litros','Cereja/Maça',24.01)
INSERT INTO [TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES ('1096818','Linha Refrescante - 700 ml - Manga','Garrafa','700 ml','Manga',7.7105)
INSERT INTO [TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES ('1022450','Festival de Sabores - 2 Litros - Açai','PET','2 Litros','Açai',38.012)



DROP TABLE [TABELA DE VENDEDORES]



CREATE TABLE [TABELA DE VENDEDORES]
( [MATRICULA] [VARCHAR](5),
[NOME] [VARCHAR](100),
[PERCENTUAL COMISSAO] [FLOAT],
[DATA DE ADMISSAO][DATE],
[FERIAS][BIT]
PRIMARY KEY ([MATRICULA])

)


INSERT INTO [TABELA DE VENDEDORES]
([MATRICULA], [NOME], [PERCENTUAL COMISSAO],[DATA DE ADMISSAO],[FERIAS])
VALUES
('00133','Marly dos Santos Gama',0.08,'15/08/2014',0)

INSERT INTO [TABELA DE VENDEDORES]
([MATRICULA], [NOME], [PERCENTUAL COMISSAO],[DATA DE ADMISSAO],[FERIAS])
VALUES
('00144','Bruno César Brandão',0.05,'15/08/2016',1)

INSERT INTO [TABELA DE VENDEDORES]
([MATRICULA], [NOME], [PERCENTUAL COMISSAO],[DATA DE ADMISSAO],[FERIAS])
VALUES
('00155','Roberta Serra',0.11,'15/08/2018',0)

INSERT INTO [TABELA DE VENDEDORES]
([MATRICULA], [NOME], [PERCENTUAL COMISSAO],[DATA DE ADMISSAO],[FERIAS])
VALUES
('00166','Pericles Alves',0.11,'15/08/2019',1)

--------------------FILTRANDO REGISTROS-------------------------

SELECT * FROM [TABELA DE PRODUTOS]

DELETE FROM [TABELA DE PRODUTOS] 
WHERE [CODIGO DO PRODUTO] = '1000889'



SELECT * FROM [TABELA DE PRODUTOS] 
WHERE [CODIGO DO PRODUTO] = '1000889'

SELECT * FROM [TABELA DE PRODUTOS] 
WHERE [SABOR] = 'Uva'

SELECT * FROM [TABELA DE PRODUTOS] 
WHERE [SABOR] = 'Limão'

DELETE FROM [TABELA DE PRODUTOS] 
WHERE [SABOR] = 'Limão'



---------------------- 1 DESAFIO DA AULA 6 --------------------------------------



SELECT [NOME], [MATRICULA] FROM [TABELA DE VENDEDORES]

SELECT [NOME DO PRODUTO] AS 'DESCRIÇÃO DO PRODUTO', [CODIGO DO PRODUTO] AS 'IDENTIFICADOR', [PRECO DE LISTA] AS 'PREÇO A PAGAR'
FROM [TABELA DE PRODUTOS]

SELECT TOP (7) [NOME],[CPF],[CIDADE] FROM [TABELA DE CLIENTES]

---------------------- 2 DESAFIO DA AULA 6 -------------------------------------

SELECT * FROM [TABELA DE VENDEDORES]
WHERE [NOME] = 'Roberta Serra'



------------------FILTRANDO REGISTROS MAIOR,MENOR,DIFERENTE----------------------


SELECT * FROM [TABELA DE PRODUTOS]

SELECT * FROM [TABELA DE PRODUTOS] WHERE EMBALAGEM = 'PET'

SELECT * FROM [TABELA DE PRODUTOS] WHERE [PREÇO DE LISTA] = 4.555

SELECT * FROM [TABELA DE PRODUTOS] WHERE [PREÇO DE LISTA] > 10

SELECT * FROM [TABELA DE PRODUTOS] WHERE [PREÇO DE LISTA] < 10

SELECT * FROM [TABELA DE PRODUTOS] WHERE [PREÇO DE LISTA] <= 4.555

SELECT * FROM [TABELA DE PRODUTOS] WHERE [PREÇO DE LISTA] >= 4.555

SELECT * FROM [TABELA DE PRODUTOS] WHERE EMBALAGEM <= 'Lata'

SELECT * FROM [TABELA DE PRODUTOS] WHERE EMBALAGEM <> 'Lata'

SELECT * FROM [TABELA DE PRODUTOS] WHERE [PREÇO DE LISTA] <> 4.555


------------------------- 3 DESAFIO DA AULA 6 -----------------------------------



SELECT * FROM [TABELA DE VENDEDORES] WHERE [PERCENTUAL COMISSAO] > 0.10



-----------------------FILTRANDO POR DATAS----------------------------------------

SELECT * FROM [TABELA DE CLIENTES]

SELECT * FROM [TABELA DE CLIENTES] WHERE [DATA DE NASCIMENTO] = '1995-09-11'

SELECT * FROM [TABELA DE CLIENTES] WHERE [DATA DE NASCIMENTO] >= '1995-09-11'

SELECT * FROM [TABELA DE CLIENTES] WHERE [DATA DE NASCIMENTO] <= '1995-09-11'

SELECT * FROM [TABELA DE CLIENTES]
WHERE [DATA DE NASCIMENTO] >= '1995-01-01' AND [DATA DE NASCIMENTO]<='1995-12-31'


SELECT * FROM [TABELA DE CLIENTES] WHERE YEAR([DATA DE NASCIMENTO]) = 1995 

SELECT * FROM [TABELA DE CLIENTES] WHERE YEAR([DATA DE NASCIMENTO]) < 1995 

SELECT * FROM [TABELA DE CLIENTES] WHERE MONTH([DATA DE NASCIMENTO]) = 12

SELECT * FROM [TABELA DE CLIENTES] WHERE DAY([DATA DE NASCIMENTO]) = 11


SELECT MONTH([DATA DE NASCIMENTO]) AS 'MES' FROM [TABELA DE CLIENTES]
WHERE YEAR ([DATA DE NASCIMENTO]) = 1995

SELECT [NOME] AS 'NOME DO CLIENTE',YEAR([DATA DE NASCIMENTO]) AS 'ANO' ,MONTH([DATA DE NASCIMENTO]) AS 'MES'  FROM [TABELA DE CLIENTES]
WHERE YEAR ([DATA DE NASCIMENTO]) = 1995

-----------------------USANDO FOREIGN KEY----------------------------------------

USE ESQUINA_VENDAS
CREATE TABLE [TABELA DE NOTAS FISCAIS]
(
[CPF][VARCHAR] (11) NOT NULL,
[MATRICULA][VARCHAR](5) NOT NULL,
[DATA][DATE],
[NUMERO][VARCHAR](6),
[IMPOSTO][FLOAT],
PRIMARY KEY([NUMERO]),

FOREIGN KEY([MATRICULA]) REFERENCES [TABELA DE VENDEDORES]([MATRICULA]),
FOREIGN KEY([CPF]) REFERENCES [TABELA DE CLIENTES]([CPF])
)

CREATE TABLE [TABELA ITENS NOTAS FISCAIS]
(
 [NUMERO][VARCHAR](6) NOT NULL,
 [CODIGO DO PRODUTO][VARCHAR](10) NOT NULL, 
 [QUANTIDADE][INT],
 [PRECO][FLOAT],

 PRIMARY KEY ([NUMERO],[CODIGO DO PRODUTO]),
 FOREIGN KEY([NUMERO]) REFERENCES [TABELA DE NOTAS FISCAIS]([NUMERO]),
 FOREIGN KEY([CODIGO DO PRODUTO]) REFERENCES [TABELA DE PRODUTOS]([CODIGO DO PRODUTO]),

)
