-- NOVO TESTE PARA BACKUP PASSO A PASSO COM EXEMPLO DE POLÍTICA DE BACKUP EMPRESARIAL

-- NOVO DB
CREATE DATABASE TESTE_BACKUP

USE TESTE_BACKUP

-- CRIANDO TABELA DE CONTROLE
CREATE TABLE CTRL_BACKUP (POS INT)

-- INSERINDO REGISTRO
INSERT INTO CTRL_BACKUP (POS) VALUES (1)

-- VERIFICANDO REGISTROS DA TABELA
SELECT * FROM CTRL_BACKUP

--> BACKUP FULL INICIAL ÀS 1:00 AM
BACKUP DATABASE TESTE_BACKUP TO DISK = 'C:\SQL_BKP\TESTE_BACKUP.BAK' WITH INIT

-- INSERINDO REGISTRO
INSERT INTO CTRL_BACKUP (POS) VALUES (2)

--> BACKUP LOG DE TRANSAÇÃO DAS 4:00 ÀS 8:00 AM DE 2 EM 2 HORAS

-- BACKUP LOG DE TRANSAÇÃO ÀS 4:00
BACKUP LOG TESTE_BACKUP TO DISK = 'C:\SQL_BKP\TESTE_BACKUP.BAK' WITH NOINIT

-- INSERINDO REGISTRO
INSERT INTO CTRL_BACKUP (POS) VALUES (3)

-- BACKUP LOG DE TRANSAÇÃO ÀS 6:00
BACKUP LOG TESTE_BACKUP TO DISK = 'C:\SQL_BKP\TESTE_BACKUP.BAK' WITH NOINIT

-- INSERINDO REGISTRO
INSERT INTO CTRL_BACKUP (POS) VALUES (4)

-- BACKUP LOG DE TRANSAÇÃO ÀS 8:00
BACKUP LOG TESTE_BACKUP TO DISK = 'C:\SQL_BKP\TESTE_BACKUP.BAK' WITH NOINIT

-- INSERINDO REGISTRO
INSERT INTO CTRL_BACKUP (POS) VALUES (5)

--> BACKUP DIFFERENTIAL ÀS 9:00
BACKUP DATABASE TESTE_BACKUP TO DISK = 'C:\SQL_BKP\TESTE_BACKUP.BAK' WITH DIFFERENTIAL

--> BACKUP LOG DE TRANSAÇÃO DAS 10:00 ÀS 14:00 DE 2 EM 2 HORAS

-- INSERINDO REGISTRO
INSERT INTO CTRL_BACKUP (POS) VALUES (6)

-- BACKUP LOG DE TRANSAÇÃO ÀS 10:00
BACKUP LOG TESTE_BACKUP TO DISK = 'C:\SQL_BKP\TESTE_BACKUP.BAK' WITH NOINIT

-- INSERINDO REGISTRO
INSERT INTO CTRL_BACKUP (POS) VALUES (7)

-- BACKUP LOG DE TRANSAÇÃO ÀS 12:00
BACKUP LOG TESTE_BACKUP TO DISK = 'C:\SQL_BKP\TESTE_BACKUP.BAK' WITH NOINIT

-- INSERINDO REGISTRO
INSERT INTO CTRL_BACKUP (POS) VALUES (8)

-- BACKUP LOG DE TRANSAÇÃO ÀS 14:00
BACKUP LOG TESTE_BACKUP TO DISK = 'C:\SQL_BKP\TESTE_BACKUP.BAK' WITH NOINIT

-- INSERINDO REGISTRO
INSERT INTO CTRL_BACKUP (POS) VALUES (9)

--> BACKUP DIFFERENTIAL ÀS 14:00
BACKUP DATABASE TESTE_BACKUP TO DISK = 'C:\SQL_BKP\TESTE_BACKUP.BAK' WITH DIFFERENTIAL

--> BACKUP LOG DE TRANSAÇÃO DAS 15:00 ÀS 21:00 DE 2 EM 2 HORAS

-- INSERINDO REGISTRO
INSERT INTO CTRL_BACKUP (POS) VALUES (10)

-- BACKUP LOG DE TRANSAÇÃO ÀS 15:00
BACKUP LOG TESTE_BACKUP TO DISK = 'C:\SQL_BKP\TESTE_BACKUP.BAK' WITH NOINIT

-- INSERINDO REGISTRO
INSERT INTO CTRL_BACKUP (POS) VALUES (11)

-- BACKUP LOG DE TRANSAÇÃO ÀS 17:00
BACKUP LOG TESTE_BACKUP TO DISK = 'C:\SQL_BKP\TESTE_BACKUP.BAK' WITH NOINIT

-- INSERINDO REGISTRO
INSERT INTO CTRL_BACKUP (POS) VALUES (12)

-- BACKUP LOG DE TRANSAÇÃO ÀS 19:00
BACKUP LOG TESTE_BACKUP TO DISK = 'C:\SQL_BKP\TESTE_BACKUP.BAK' WITH NOINIT

-- INSERINDO REGISTRO
INSERT INTO CTRL_BACKUP (POS) VALUES (13)

-- BACKUP LOG DE TRANSAÇÃO ÀS 21:00
BACKUP LOG TESTE_BACKUP TO DISK = 'C:\SQL_BKP\TESTE_BACKUP.BAK' WITH NOINIT


--	SE QUISERMOS RECUPERAR OS DADOS DAS 17:30 |
--		RECUPERAR PRIMEIRO O FULL (1:00)
--			DEPOIS O DIFERENCIAL MAIS PRÓXIMO DO HORÁRIO QUE DEU PROBLEMA (14:00)
--				DEPOIS OS ARQUIVOS DE TRANSAÇÃO MAIS PRÓXIMOS DO HORÁRIO (15:00, 17:00)


-- RESTAURAÇÃO DO BANCO DE DADOS

USE MASTER

-- ALTERANDO SOMENTE PARA UM ÚNICO USUÁRIO PARA SEGURANÇA
ALTER DATABASE TESTE_BACKUP SET SINGLE_USER WITH ROLLBACK IMMEDIATE

DROP DATABASE TESTE_BACKUP

-- VERIFICAÇÃO DO ARQUIVO DE BACKUP (1 = VÁLIDO)
RESTORE VERIFYONLY FROM DISK = 'C:\SQL_BKP\TESTE_BACKUP.BAK'

-- VERIFICAÇÃO DO CABEÇALHO DOS BACKUPS
RESTORE HEADERONLY FROM DISK = 'C:\SQL_BKP\TESTE_BACKUP.BAK'

-- BACKUP FULL INICIAL | 1:00 AM
RESTORE DATABASE TESTE_BACKUP FROM DISK = 'C:\SQL_BKP\TESTE_BACKUP.BAK' WITH FILE = 1, NORECOVERY

-- BACKUP DIFFERENTIAL | 14:00
RESTORE DATABASE TESTE_BACKUP FROM DISK = 'C:\SQL_BKP\TESTE_BACKUP.BAK' WITH FILE = 9, NORECOVERY

-- BACKUP LOG | 15:00
RESTORE DATABASE TESTE_BACKUP FROM DISK = 'C:\SQL_BKP\TESTE_BACKUP.BAK' WITH FILE = 10, NORECOVERY

-- BACKUP LOG | 17:00
RESTORE DATABASE TESTE_BACKUP FROM DISK = 'C:\SQL_BKP\TESTE_BACKUP.BAK' WITH FILE = 11, RECOVERY


-- VERIFICA SE DEU CERTO (ATÉ A POS 11)

USE TESTE_BACKUP

SELECT * FROM CTRL_BACKUP


-- PARA ADICIONAR DESCRIÇÃO NO BACKUP
BACKUP LOG TESTE_BACKUP TO DISK = 'C:\SQL_BKP\TESTE_BACKUP.BAK' WITH NOINIT, DESCRIPTION='21:00 Log de Transação'

-- ESSA É SOMENTE UMA SIMULAÇÃO, NA VIDA REAL O BACKUP É AGENDADO