USE model
CREATE TABLE TESTE(
	IDENTIFICADOR INT NOT NULL IDENTITY,
	NOME VARCHAR(20) NOT NULL
)

CREATE DATABASE SISTEMA_A

USE SISTEMA_A 
SELECT * FROM SYS.database_files

CREATE TABLE TESTE(
	IDENTIFICADOR INT NOT NULL IDENTITY,
	NOME VARCHAR(20) NOT NULL
)

CREATE DATABASE SISTEMA_B
ON PRIMARY
(NAME = SISTEMA_B, FILENAME = 'C:\TEMP SQL\SISTEMA_B.mdf', SIZE = 100MB, MAXSIZE = 200MB, FILEGROWTH = 10MB),
(NAME = SISTEMA_B_2, FILENAME = 'C:\TEMP SQL\SISTEMA_B_2.ndf', SIZE = 100MB, MAXSIZE = 200MB, FILEGROWTH = 10MB)
LOG ON (NAME = SISTEMA_B_LOG, FILENAME = 'C:\TEMP SQL\SISTEMA_B_LOG.ldf', SIZE = 100MB, MAXSIZE = 200MB, FILEGROWTH = 10MB)


USE ESQUINA_VENDAS
BACKUP DATABASE ESQUINA_VENDAS TO DISK = 'C:\TEMP SQL\ESQUINA_VENDAS.BAK' WITH INIT
BACKUP DATABASE ESQUINA_VENDAS TO DISK = 'C:\TEMP SQL\ESQUINA_VENDAS_COMPRESSION.BAK' WITH COMPRESSION