-- VER O PROCESSAMENTO DOS DADOS PELO MONITOR DE ATIVIDADES
USE ESQUINA_VENDAS

CREATE TABLE SOMA_QUANTIDADE (SOMA FLOAT)

DECLARE @MAX INT, @CONTADOR INT
SET @MAX = 3600
SET @CONTADOR = 1
WHILE @CONTADOR < @MAX
	BEGIN
		DECLARE @AUX FLOAT
		SELECT @AUX = SUM(QUANTIDADE) FROM [TABELA DE ITENS NOTAS FISCAIS]
		INSERT INTO SOMA_QUANTIDADE (SOMA) VALUES (@AUX)
		SET @CONTADOR = @CONTADOR + 1
		WAITFOR DELAY '00:00:02'
	END

SELECT * FROM SOMA_QUANTIDADE

-- VAMOS DIFICULTAR (PROCESSO MAIS PESADO) 

CREATE TABLE SOMA_QTD_2 (SOMA FLOAT)
DECLARE @MAX2 INT, @CONTADOR2 INT
SET @MAX2 = 30000000
SET @CONTADOR2 = 1

INSERT INTO SOMA_QTD_2 (SOMA) VALUES (1)
WHILE @CONTADOR2 < @MAX2
	BEGIN
		INSERT INTO SOMA_QTD_2 (SOMA)
		SELECT SOMA + @CONTADOR2 FROM SOMA_QTD_2
		SET @CONTADOR2 = @CONTADOR2 * 2
	END
INSERT INTO SOMA_QTD_2
SELECT SOMA + @CONTADOR2 FROM SOMA_QTD_2
WHERE SOMA + @CONTADOR2 <= @MAX2

SELECT SOMA, SOMA+1 AS 'SOMA + 1' FROM SOMA_QTD_2
WHERE SOMA <= 30000000

-- DIMINUINDO O BANCO
USE ESQUINA_VENDAS
ALTER DATABASE ESQUINA_VENDAS SET RECOVERY SIMPLE
DBCC SHRINKDATABASE ('ESQUINA_VENDAS', NOTRUNCATE)
DBCC SHRINKDATABASE ('ESQUINA_VENDAS', TRUNCATEONLY)
ALTER DATABASE ESQUINA_VENDAS SET RECOVERY FULL
