USE ESQUINA_VENDAS
SELECT * FROM [dbo].[TABELA DE VENDEDORES]

BEGIN TRANSACTION

UPDATE [dbo].[TABELA DE VENDEDORES]
SET [PERCENTUAL COMISSAO] = [PERCENTUAL COMISSAO]*1.15

INSERT INTO [dbo].[TABELA DE VENDEDORES] ([MATRICULA],[NOME],[PERCENTUAL COMISSAO],[DATA DE ADMISSAO],[FERIAS],[BAIRRO])
VALUES ('99999', 'João da Silva', 0.00, '2014-09-01',0,'Icaraí')

ROLLBACK 

COMMIT
