USE ESQUINA_VENDAS
SELECT DISTINCT EMBALAGEM, TAMANHO FROM [TABELA DE PRODUTOS]
where SABOR = 'Laranja'

SELECT DISTINCT BAIRRO FROM [dbo].[TABELA DE CLIENTES]
WHERE CIDADE = 'Rio de Janeiro'

SELECT TOP 10 * FROM [dbo].[TABELA DE NOTAS FISCAIS]
WHERE [DATA] = '2017-01-01'

--QUAL A MAIOR VENDA EM QUANTIDADE DO PRODUTO: Linha Refrescante - 1 Litro - Morango/Limão
SELECT [CODIGO DO PRODUTO] FROM [dbo].[TABELA DE PRODUTOS]
WHERE [NOME DO PRODUTO] = 'Linha Refrescante - 1 Litro - Morango/Limão'

SELECT TOP 1 * FROM [dbo].[TABELA DE ITENS NOTAS FISCAIS]
WHERE [CODIGO DO PRODUTO]='1101035' --CODIGO ENCONTRADO NO COMANDO ACIMA
ORDER BY [QUANTIDADE] DESC ,[PREÇO]  DESC
--END

SELECT [SABOR],SUM([PRECO DE LISTA]) AS 'PRECO' FROM [dbo].[TABELA DE PRODUTOS]
GROUP BY [SABOR]

SELECT ESTADO, SUM([LIMITE DE CREDITO]) AS 'SOMA DO LIMITE DE CREDITO' FROM [dbo].[TABELA DE CLIENTES]
GROUP BY ESTADO

SELECT ESTADO, AVG([LIMITE DE CREDITO]) AS 'MÉDIA DO LIMITE DE CREDITO' FROM [dbo].[TABELA DE CLIENTES]
GROUP BY ESTADO

SELECT [EMBALAGEM],MAX([PRECO DE LISTA]) AS 'VALOR MAIS CARO POR EMBALAGEM' FROM [dbo].[TABELA DE PRODUTOS]
GROUP BY [EMBALAGEM]

SELECT [EMBALAGEM],MIN([PRECO DE LISTA]) AS 'VALOR MAIS BARATO POR EMBALAGEM' FROM [dbo].[TABELA DE PRODUTOS]
GROUP BY [EMBALAGEM]

SELECT [EMBALAGEM],COUNT(*) AS 'CONTAGEM POR EMBALAGEM' FROM [dbo].[TABELA DE PRODUTOS]
GROUP BY [EMBALAGEM]

SELECT [BAIRRO], SUM([LIMITE DE CREDITO]) AS 'SOMA DE LIMITE DE CRÉDITO' FROM [dbo].[TABELA DE CLIENTES]
WHERE [ESTADO] = 'SP'
GROUP BY BAIRRO
ORDER BY BAIRRO DESC

--QUANTOS ITENS DE VENDA EXISTEM COM A MAIOR QUANTIDADE DE VENDA PARA O PRODUTO '1101035'
SELECT [CODIGO DO PRODUTO], MAX([QUANTIDADE]) FROM [dbo].[TABELA DE ITENS NOTAS FISCAIS]
WHERE [CODIGO DO PRODUTO] = '1101035'
GROUP BY [CODIGO DO PRODUTO] -- MAIOR QUANTIDADE

SELECT [CODIGO DO PRODUTO], COUNT(*) AS 'CONTAGEM DA MAIOR QUANTIDADE ' FROM [dbo].[TABELA DE ITENS NOTAS FISCAIS]
WHERE [CODIGO DO PRODUTO] = '1101035' AND [QUANTIDADE] = 99
GROUP BY [CODIGO DO PRODUTO]
--END