USE ESQUINA_VENDAS
-- DESAFIO AULA 16

SELECT [CPF],[IDADE],[DATA DE NASCIMENTO], DATEDIFF(YEAR,[DATA DE NASCIMENTO], GETDATE()) AS 'IDADE' 
FROM [dbo].[TABELA DE CLIENTES]

-- TRIGGER
CREATE TRIGGER TB_CLIENTES_IDADE
ON [dbo].[TABELA DE CLIENTES]
AFTER INSERT, UPDATE, DELETE
AS
BEGIN
	UPDATE [dbo].[TABELA DE CLIENTES]
	SET [IDADE] = DATEDIFF(YEAR,[DATA DE NASCIMENTO], GETDATE());
END

INSERT INTO [dbo].[TABELA DE CLIENTES]
([CPF],[NOME], [ENDERECO], [COMPLEMENTO], [CIDADE],[ESTADO],[CEP], [DATA DE NASCIMENTO],[IDADE],[SEXO],[LIMITE DE CREDITO],[VOLUME DE COMPRA],[PRIMEIRA COMPRA])
VALUES('51073366200', 'Klécio Lira','Rua Conde do Bonfim','','Rio de Janeiro','RJ', '22020001','2001-01-01',1,'M',12000000,22000,1)

SELECT * FROM [dbo].[TABELA DE CLIENTES]
WHERE [CPF]='51073366200'

-- CHECK
CREATE TABLE CLIENTE_TESTE
(
	ID INT IDENTITY NOT NULL,
	NOME VARCHAR (20),
	IDADE INT,
	CIDADE VARCHAR (20),

	CHECK ( IDADE >= 18)
)

INSERT INTO [dbo].[CLIENTE_TESTE] (NOME, IDADE, CIDADE)
VALUES ('Maria', 17, 'Rio de Janeiro')

CREATE TABLE CLIENTE_TESTE_2
(
	ID INT IDENTITY NOT NULL,
	NOME VARCHAR (20),
	IDADE INT,
	CIDADE VARCHAR (20),

	CHECK ( IDADE >= 18 AND CIDADE = 'Rio de Janeiro')
)

INSERT INTO [dbo].[CLIENTE_TESTE_2] (NOME, IDADE, CIDADE)
VALUES ('Maria', 18, 'Rio de Janeir')

DROP TABLE CLIENTE_TESTE_2
DROP TABLE CLIENTE_TESTE

-- RESTRIÇÕES
CREATE TABLE CLIENTE_TESTE
(
	ID INT IDENTITY NOT NULL,
	NOME VARCHAR (20) NOT NULL,
	IDADE INT NOT NULL,
	CIDADE VARCHAR (20) NOT NULL,
	SEXO CHAR(1) NOT NULL,
	EMAIL VARCHAR (30) NOT NULL,
	NUMERO VARCHAR (6) NOT NULL,

	CONSTRAINT CK_IDADE CHECK (IDADE >= 18),
	CONSTRAINT CK_SEXO CHECK (SEXO IN ('F','M')),
	--CONSTRAINT PK_ID PRIMARY KEY (ID),
	CONSTRAINT UQ_EMAIL UNIQUE (EMAIL),
	--CONSTRAINT FK_CLIENTE_TESTE_TABELA_DE_NOTAS_FISCAIS FOREIGN KEY (NUMERO) REFERENCES [dbo].[TABELA DE NOTAS FISCAIS] (NUMERO)
)
INSERT INTO [dbo].[CLIENTE_TESTE] (NOME, IDADE, CIDADE, SEXO, EMAIL, NUMERO)
VALUES ('Maria', 18, 'Rio de Janeiro', 'F', 'maria@teste.com', '011111')

SELECT * FROM [dbo].[CLIENTE_TESTE]

-- ALTER TABLE

ALTER TABLE [dbo].[CLIENTE_TESTE]
	ADD CONSTRAINT PK_ID PRIMARY KEY (ID)

ALTER TABLE [dbo].[CLIENTE_TESTE]
	ADD CONSTRAINT FK_CLIENTE_TESTE_TABELA_DE_NOTAS_FISCAIS FOREIGN KEY (NUMERO) REFERENCES [dbo].[TABELA DE NOTAS FISCAIS] (NUMERO)

ALTER TABLE [dbo].[CLIENTE_TESTE]
	DROP CONSTRAINT PK_ID

CREATE TABLE PRODUTO
(
	IDPRODUTO INT IDENTITY NOT NULL,
	DESCRICAO VARCHAR (30) NOT NULL,
	PRECO FLOAT NOT NULL
)

ALTER TABLE PRODUTO
	ADD FRETE FLOAT NOT NULL

ALTER TABLE PRODUTO
	DROP COLUMN FRETE

ALTER TABLE PRODUTO
	ALTER COLUMN FRETE DECIMAL(10,2)

-- VARIAVEL --> RODAR TODO O CONJUNTO

DECLARE @TESTE VARCHAR (20)

SET @TESTE = 'SQL SERVER'

SELECT @TESTE AS 'TESTE'

-- DESAFIO 
DECLARE @CLIENTE  VARCHAR (10)
DECLARE @IDADE INT
DECLARE @DATANASCIMENTO DATE 
DECLARE @CUSTO DECIMAL (10,2)

SET @CLIENTE = 'JOÃO'
SET @IDADE = 10
SET @DATANASCIMENTO = '2007-01-10'
SET @CUSTO = 10.23

SELECT @CLIENTE AS 'CLIENTE', @IDADE AS 'IDADE', @DATANASCIMENTO AS 'DATA DE NASCIMENTO', @CUSTO AS 'CUSTO'

-- END

-- COM INSERT
DECLARE @MATRICULA VARCHAR(5), @NOME VARCHAR(100), @PERCENTUAL FLOAT, @DATA DATE, @FERIAS BIT, @BAIRRO VARCHAR(100)
SET @MATRICULA = '00241'
SET @NOME = 'VITÓRIA MARIA'
SET @PERCENTUAL = 0.15
SET @DATA = '20210608'
SET @FERIAS = 0
SET @BAIRRO = 'MEIER'

INSERT INTO [dbo].[TABELA DE VENDEDORES] ([MATRICULA], [NOME], [PERCENTUAL COMISSAO], [DATA DE ADMISSAO], [FERIAS], [BAIRRO])
VALUES (@MATRICULA, @NOME, @PERCENTUAL, @DATA, @FERIAS, @BAIRRO)

-- DESAFIO

DECLARE @NUMNOTAS INT

SET @NUMNOTAS = (SELECT COUNT(NUMERO) AS 'QTD NOTAS' FROM [dbo].[TABELA DE NOTAS FISCAIS]
WHERE DATA = '2017-01-01'
GROUP BY DATA)

PRINT @NUMNOTAS

